// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: subpkg/subproto.proto

package subpkg

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SubObject struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubObject) Reset()         { *m = SubObject{} }
func (m *SubObject) String() string { return proto.CompactTextString(m) }
func (*SubObject) ProtoMessage()    {}
func (*SubObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_896c12f092e0b025, []int{0}
}
func (m *SubObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubObject.Unmarshal(m, b)
}
func (m *SubObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubObject.Marshal(b, m, deterministic)
}
func (m *SubObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubObject.Merge(m, src)
}
func (m *SubObject) XXX_Size() int {
	return xxx_messageInfo_SubObject.Size(m)
}
func (m *SubObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SubObject.DiscardUnknown(m)
}

var xxx_messageInfo_SubObject proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SubObject)(nil), "subpkg.SubObject")
}

func init() { proto.RegisterFile("subpkg/subproto.proto", fileDescriptor_896c12f092e0b025) }

var fileDescriptor_896c12f092e0b025 = []byte{
	// 71 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2e, 0x4d, 0x2a,
	0xc8, 0x4e, 0xd7, 0x07, 0x51, 0x45, 0xf9, 0x25, 0xf9, 0x7a, 0x60, 0x52, 0x88, 0x0d, 0x22, 0x2c,
	0x25, 0x92, 0x9e, 0x9f, 0x9e, 0x0f, 0x16, 0xd2, 0x07, 0xb1, 0x20, 0xb2, 0x4a, 0xdc, 0x5c, 0x9c,
	0xc1, 0xa5, 0x49, 0xfe, 0x49, 0x59, 0xa9, 0xc9, 0x25, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81,
	0x5d, 0x36, 0x4c, 0x42, 0x00, 0x00, 0x00,
}
