// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: issue444.proto

package issue444

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SizeMe struct {
	Foo                  string   `protobuf:"bytes,1,opt,name=foo,proto3" json:"foo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SizeMe) Reset()         { *m = SizeMe{} }
func (m *SizeMe) String() string { return proto.CompactTextString(m) }
func (*SizeMe) ProtoMessage()    {}
func (*SizeMe) Descriptor() ([]byte, []int) {
	return fileDescriptor_e39b8ab75bd9d8cd, []int{0}
}
func (m *SizeMe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SizeMe.Unmarshal(m, b)
}
func (m *SizeMe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SizeMe.Marshal(b, m, deterministic)
}
func (m *SizeMe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SizeMe.Merge(m, src)
}
func (m *SizeMe) XXX_Size() int {
	return xxx_messageInfo_SizeMe.Size(m)
}
func (m *SizeMe) XXX_DiscardUnknown() {
	xxx_messageInfo_SizeMe.DiscardUnknown(m)
}

var xxx_messageInfo_SizeMe proto.InternalMessageInfo

func (m *SizeMe) GetFoo() string {
	if m != nil {
		return m.Foo
	}
	return ""
}

func init() {
	proto.RegisterType((*SizeMe)(nil), "issue444.SizeMe")
}

func init() { proto.RegisterFile("issue444.proto", fileDescriptor_e39b8ab75bd9d8cd) }

var fileDescriptor_e39b8ab75bd9d8cd = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2c, 0x2e, 0x2e,
	0x4d, 0x35, 0x31, 0x31, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0xa5, 0x0c,
	0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x93, 0xf3, 0x8b, 0x73, 0xf3,
	0x8b, 0xf5, 0xd3, 0xf3, 0xd3, 0xf3, 0xc1, 0xca, 0xd0, 0x58, 0x10, 0xbd, 0x4a, 0x52, 0x5c, 0x6c,
	0xc1, 0x99, 0x55, 0xa9, 0xbe, 0xa9, 0x42, 0x02, 0x5c, 0xcc, 0x69, 0xf9, 0xf9, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x13, 0xcb, 0x83, 0x47, 0x72, 0x8c, 0x49, 0x6c, 0x60, 0x85,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x13, 0xd6, 0x0c, 0x76, 0x00, 0x00, 0x00,
}

func (m *SizeMe) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Foo)
	if l > 0 {
		n += 1 + l + sovIssue444(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovIssue444(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIssue444(x uint64) (n int) {
	return sovIssue444(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
