// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oneof3/combos/marshaler/one.proto

package oneof3_combos_marshaler

import (
	bytes "bytes"
	compress_gzip "compress/gzip"
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	github_com_cosmos_gogoproto_proto "github.com/cosmos/gogoproto/proto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_protoc_gen_gogo_descriptor "github.com/cosmos/gogoproto/protoc-gen-gogo/descriptor"
	io_ioutil "io/ioutil"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Subby struct {
	Sub                  string   `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subby) Reset()      { *m = Subby{} }
func (*Subby) ProtoMessage() {}
func (*Subby) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d1747744692eae7, []int{0}
}
func (m *Subby) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subby.Unmarshal(m, b)
}
func (m *Subby) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Subby.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Subby) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subby.Merge(m, src)
}
func (m *Subby) XXX_Size() int {
	return m.Size()
}
func (m *Subby) XXX_DiscardUnknown() {
	xxx_messageInfo_Subby.DiscardUnknown(m)
}

var xxx_messageInfo_Subby proto.InternalMessageInfo

type SampleOneOf struct {
	// Types that are valid to be assigned to TestOneof:
	//
	//	*SampleOneOf_Field1
	//	*SampleOneOf_Field2
	//	*SampleOneOf_Field3
	//	*SampleOneOf_Field4
	//	*SampleOneOf_Field5
	//	*SampleOneOf_Field6
	//	*SampleOneOf_Field7
	//	*SampleOneOf_Field8
	//	*SampleOneOf_Field9
	//	*SampleOneOf_Field10
	//	*SampleOneOf_Field11
	//	*SampleOneOf_Field12
	//	*SampleOneOf_Field13
	//	*SampleOneOf_Field14
	//	*SampleOneOf_Field15
	//	*SampleOneOf_SubMessage
	TestOneof            isSampleOneOf_TestOneof `protobuf_oneof:"test_oneof"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SampleOneOf) Reset()      { *m = SampleOneOf{} }
func (*SampleOneOf) ProtoMessage() {}
func (*SampleOneOf) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d1747744692eae7, []int{1}
}
func (m *SampleOneOf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SampleOneOf.Unmarshal(m, b)
}
func (m *SampleOneOf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SampleOneOf.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SampleOneOf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SampleOneOf.Merge(m, src)
}
func (m *SampleOneOf) XXX_Size() int {
	return m.Size()
}
func (m *SampleOneOf) XXX_DiscardUnknown() {
	xxx_messageInfo_SampleOneOf.DiscardUnknown(m)
}

var xxx_messageInfo_SampleOneOf proto.InternalMessageInfo

type isSampleOneOf_TestOneof interface {
	isSampleOneOf_TestOneof()
	Equal(interface{}) bool
	VerboseEqual(interface{}) error
	MarshalTo([]byte) (int, error)
	Size() int
	Compare(interface{}) int
}

type SampleOneOf_Field1 struct {
	Field1 float64 `protobuf:"fixed64,1,opt,name=Field1,proto3,oneof" json:"Field1,omitempty"`
}
type SampleOneOf_Field2 struct {
	Field2 float32 `protobuf:"fixed32,2,opt,name=Field2,proto3,oneof" json:"Field2,omitempty"`
}
type SampleOneOf_Field3 struct {
	Field3 int32 `protobuf:"varint,3,opt,name=Field3,proto3,oneof" json:"Field3,omitempty"`
}
type SampleOneOf_Field4 struct {
	Field4 int64 `protobuf:"varint,4,opt,name=Field4,proto3,oneof" json:"Field4,omitempty"`
}
type SampleOneOf_Field5 struct {
	Field5 uint32 `protobuf:"varint,5,opt,name=Field5,proto3,oneof" json:"Field5,omitempty"`
}
type SampleOneOf_Field6 struct {
	Field6 uint64 `protobuf:"varint,6,opt,name=Field6,proto3,oneof" json:"Field6,omitempty"`
}
type SampleOneOf_Field7 struct {
	Field7 int32 `protobuf:"zigzag32,7,opt,name=Field7,proto3,oneof" json:"Field7,omitempty"`
}
type SampleOneOf_Field8 struct {
	Field8 int64 `protobuf:"zigzag64,8,opt,name=Field8,proto3,oneof" json:"Field8,omitempty"`
}
type SampleOneOf_Field9 struct {
	Field9 uint32 `protobuf:"fixed32,9,opt,name=Field9,proto3,oneof" json:"Field9,omitempty"`
}
type SampleOneOf_Field10 struct {
	Field10 int32 `protobuf:"fixed32,10,opt,name=Field10,proto3,oneof" json:"Field10,omitempty"`
}
type SampleOneOf_Field11 struct {
	Field11 uint64 `protobuf:"fixed64,11,opt,name=Field11,proto3,oneof" json:"Field11,omitempty"`
}
type SampleOneOf_Field12 struct {
	Field12 int64 `protobuf:"fixed64,12,opt,name=Field12,proto3,oneof" json:"Field12,omitempty"`
}
type SampleOneOf_Field13 struct {
	Field13 bool `protobuf:"varint,13,opt,name=Field13,proto3,oneof" json:"Field13,omitempty"`
}
type SampleOneOf_Field14 struct {
	Field14 string `protobuf:"bytes,14,opt,name=Field14,proto3,oneof" json:"Field14,omitempty"`
}
type SampleOneOf_Field15 struct {
	Field15 []byte `protobuf:"bytes,15,opt,name=Field15,proto3,oneof" json:"Field15,omitempty"`
}
type SampleOneOf_SubMessage struct {
	SubMessage *Subby `protobuf:"bytes,16,opt,name=sub_message,json=subMessage,proto3,oneof" json:"sub_message,omitempty"`
}

func (*SampleOneOf_Field1) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field2) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field3) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field4) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field5) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field6) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field7) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field8) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field9) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field10) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field11) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field12) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field13) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field14) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field15) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_SubMessage) isSampleOneOf_TestOneof() {}

func (m *SampleOneOf) GetTestOneof() isSampleOneOf_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *SampleOneOf) GetField1() float64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field1); ok {
		return x.Field1
	}
	return 0
}

func (m *SampleOneOf) GetField2() float32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field2); ok {
		return x.Field2
	}
	return 0
}

func (m *SampleOneOf) GetField3() int32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field3); ok {
		return x.Field3
	}
	return 0
}

func (m *SampleOneOf) GetField4() int64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field4); ok {
		return x.Field4
	}
	return 0
}

func (m *SampleOneOf) GetField5() uint32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field5); ok {
		return x.Field5
	}
	return 0
}

func (m *SampleOneOf) GetField6() uint64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field6); ok {
		return x.Field6
	}
	return 0
}

func (m *SampleOneOf) GetField7() int32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field7); ok {
		return x.Field7
	}
	return 0
}

func (m *SampleOneOf) GetField8() int64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field8); ok {
		return x.Field8
	}
	return 0
}

func (m *SampleOneOf) GetField9() uint32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field9); ok {
		return x.Field9
	}
	return 0
}

func (m *SampleOneOf) GetField10() int32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field10); ok {
		return x.Field10
	}
	return 0
}

func (m *SampleOneOf) GetField11() uint64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field11); ok {
		return x.Field11
	}
	return 0
}

func (m *SampleOneOf) GetField12() int64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field12); ok {
		return x.Field12
	}
	return 0
}

func (m *SampleOneOf) GetField13() bool {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field13); ok {
		return x.Field13
	}
	return false
}

func (m *SampleOneOf) GetField14() string {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field14); ok {
		return x.Field14
	}
	return ""
}

func (m *SampleOneOf) GetField15() []byte {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field15); ok {
		return x.Field15
	}
	return nil
}

func (m *SampleOneOf) GetSubMessage() *Subby {
	if x, ok := m.GetTestOneof().(*SampleOneOf_SubMessage); ok {
		return x.SubMessage
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SampleOneOf) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SampleOneOf_Field1)(nil),
		(*SampleOneOf_Field2)(nil),
		(*SampleOneOf_Field3)(nil),
		(*SampleOneOf_Field4)(nil),
		(*SampleOneOf_Field5)(nil),
		(*SampleOneOf_Field6)(nil),
		(*SampleOneOf_Field7)(nil),
		(*SampleOneOf_Field8)(nil),
		(*SampleOneOf_Field9)(nil),
		(*SampleOneOf_Field10)(nil),
		(*SampleOneOf_Field11)(nil),
		(*SampleOneOf_Field12)(nil),
		(*SampleOneOf_Field13)(nil),
		(*SampleOneOf_Field14)(nil),
		(*SampleOneOf_Field15)(nil),
		(*SampleOneOf_SubMessage)(nil),
	}
}

func init() {
	proto.RegisterType((*Subby)(nil), "oneof3.combos.marshaler.Subby")
	proto.RegisterType((*SampleOneOf)(nil), "oneof3.combos.marshaler.SampleOneOf")
}

func init() { proto.RegisterFile("oneof3/combos/marshaler/one.proto", fileDescriptor_9d1747744692eae7) }

var fileDescriptor_9d1747744692eae7 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd2, 0xbd, 0x6e, 0xdb, 0x30,
	0x10, 0x07, 0x70, 0x5e, 0x1c, 0xdb, 0x09, 0xed, 0x34, 0xae, 0x50, 0xa0, 0xd7, 0x0c, 0x07, 0x36,
	0x13, 0x27, 0xb9, 0x96, 0xec, 0x7c, 0x8c, 0xcd, 0x50, 0x78, 0x29, 0x02, 0x38, 0x0f, 0x10, 0x58,
	0x2d, 0xe3, 0x16, 0xb0, 0xcc, 0xc0, 0xb4, 0x86, 0x6e, 0x79, 0x9c, 0x8c, 0x1d, 0xfb, 0x08, 0x19,
	0x33, 0x76, 0x8c, 0x98, 0xa5, 0xa3, 0x47, 0x8f, 0x85, 0xa5, 0xf6, 0x38, 0x65, 0x3b, 0xf2, 0xf7,
	0xbf, 0x81, 0xbc, 0x93, 0xef, 0xed, 0xc2, 0xd8, 0x9b, 0xb4, 0xff, 0xc5, 0xe6, 0x99, 0x75, 0xfd,
	0x7c, 0xba, 0x74, 0xdf, 0xa6, 0x73, 0xb3, 0xec, 0xdb, 0x85, 0x89, 0x6f, 0x97, 0x76, 0x65, 0xa3,
	0xb7, 0x75, 0x24, 0xae, 0x23, 0x31, 0x47, 0x8e, 0xde, 0xcc, 0xec, 0xcc, 0x56, 0x99, 0xfe, 0xb6,
	0xaa, 0xe3, 0xc7, 0xef, 0x64, 0xf3, 0xaa, 0xc8, 0xb2, 0x1f, 0x51, 0x4f, 0x36, 0x5c, 0x91, 0x21,
	0x28, 0xd0, 0xfb, 0x93, 0x6d, 0x79, 0xbc, 0x6e, 0xc8, 0xce, 0xd5, 0x34, 0xbf, 0x9d, 0x9b, 0xcb,
	0x85, 0xb9, 0xbc, 0x89, 0x50, 0xb6, 0x3e, 0x7d, 0x37, 0xf3, 0xaf, 0x83, 0x2a, 0x04, 0x63, 0x31,
	0xf9, 0x77, 0x66, 0x49, 0x70, 0x47, 0x81, 0xde, 0x61, 0x49, 0x58, 0x52, 0x6c, 0x28, 0xd0, 0x4d,
	0x96, 0x94, 0x65, 0x88, 0xbb, 0x0a, 0x74, 0x83, 0x65, 0xc8, 0x32, 0xc2, 0xa6, 0x02, 0x7d, 0xc0,
	0x32, 0x62, 0x39, 0xc1, 0x96, 0x02, 0xbd, 0xcb, 0x72, 0xc2, 0x72, 0x8a, 0x6d, 0x05, 0xfa, 0x35,
	0xcb, 0x29, 0xcb, 0x19, 0xee, 0x29, 0xd0, 0x11, 0xcb, 0x19, 0xcb, 0x39, 0xee, 0x2b, 0xd0, 0x6d,
	0x96, 0xf3, 0xe8, 0x48, 0xb6, 0xeb, 0x97, 0x7d, 0x40, 0xa9, 0x40, 0x1f, 0x8e, 0xc5, 0xe4, 0xff,
	0x45, 0xb0, 0x01, 0x76, 0x14, 0xe8, 0x56, 0xb0, 0x41, 0xb0, 0x04, 0xbb, 0x0a, 0x74, 0x2f, 0x58,
	0x12, 0x2c, 0xc5, 0x03, 0x05, 0x7a, 0x2f, 0x58, 0x1a, 0x6c, 0x88, 0xaf, 0xb6, 0xff, 0x1f, 0x6c,
	0x18, 0x6c, 0x84, 0x87, 0x0a, 0x74, 0x37, 0xd8, 0x28, 0xfa, 0x28, 0x3b, 0xae, 0xc8, 0xae, 0x73,
	0xe3, 0xdc, 0x74, 0x66, 0xb0, 0xa7, 0x40, 0x77, 0x12, 0x8a, 0x5f, 0xd8, 0x80, 0xb8, 0x1a, 0xf4,
	0x58, 0x4c, 0xa4, 0x2b, 0xb2, 0xcf, 0x75, 0xcf, 0x45, 0x57, 0xca, 0x95, 0x71, 0xab, 0xeb, 0xaa,
	0xe7, 0x62, 0xfc, 0x50, 0x92, 0x78, 0x2c, 0x49, 0xfc, 0x2e, 0x49, 0x3c, 0x95, 0x04, 0xeb, 0x92,
	0x60, 0x53, 0x12, 0xdc, 0x79, 0x82, 0x7b, 0x4f, 0xf0, 0xd3, 0x13, 0xfc, 0xf2, 0x04, 0x0f, 0x9e,
	0xe0, 0xd1, 0x93, 0x78, 0xf2, 0x04, 0x7f, 0x3c, 0x89, 0xb5, 0x27, 0xd8, 0x78, 0x12, 0x77, 0xcf,
	0x24, 0xee, 0x9f, 0x09, 0xb2, 0x56, 0xb5, 0x5e, 0xe9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9,
	0xc1, 0x5d, 0x04, 0xb2, 0x02, 0x00, 0x00,
}

func (this *Subby) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*Subby)
	if !ok {
		that2, ok := that.(Subby)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Sub != that1.Sub {
		if this.Sub < that1.Sub {
			return -1
		}
		return 1
	}
	if c := bytes.Compare(this.XXX_unrecognized, that1.XXX_unrecognized); c != 0 {
		return c
	}
	return 0
}
func (this *SampleOneOf) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf)
	if !ok {
		that2, ok := that.(SampleOneOf)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if that1.TestOneof == nil {
		if this.TestOneof != nil {
			return 1
		}
	} else if this.TestOneof == nil {
		return -1
	} else {
		thisType := -1
		switch this.TestOneof.(type) {
		case *SampleOneOf_Field1:
			thisType = 0
		case *SampleOneOf_Field2:
			thisType = 1
		case *SampleOneOf_Field3:
			thisType = 2
		case *SampleOneOf_Field4:
			thisType = 3
		case *SampleOneOf_Field5:
			thisType = 4
		case *SampleOneOf_Field6:
			thisType = 5
		case *SampleOneOf_Field7:
			thisType = 6
		case *SampleOneOf_Field8:
			thisType = 7
		case *SampleOneOf_Field9:
			thisType = 8
		case *SampleOneOf_Field10:
			thisType = 9
		case *SampleOneOf_Field11:
			thisType = 10
		case *SampleOneOf_Field12:
			thisType = 11
		case *SampleOneOf_Field13:
			thisType = 12
		case *SampleOneOf_Field14:
			thisType = 13
		case *SampleOneOf_Field15:
			thisType = 14
		case *SampleOneOf_SubMessage:
			thisType = 15
		default:
			panic(fmt.Sprintf("compare: unexpected type %T in oneof", this.TestOneof))
		}
		that1Type := -1
		switch that1.TestOneof.(type) {
		case *SampleOneOf_Field1:
			that1Type = 0
		case *SampleOneOf_Field2:
			that1Type = 1
		case *SampleOneOf_Field3:
			that1Type = 2
		case *SampleOneOf_Field4:
			that1Type = 3
		case *SampleOneOf_Field5:
			that1Type = 4
		case *SampleOneOf_Field6:
			that1Type = 5
		case *SampleOneOf_Field7:
			that1Type = 6
		case *SampleOneOf_Field8:
			that1Type = 7
		case *SampleOneOf_Field9:
			that1Type = 8
		case *SampleOneOf_Field10:
			that1Type = 9
		case *SampleOneOf_Field11:
			that1Type = 10
		case *SampleOneOf_Field12:
			that1Type = 11
		case *SampleOneOf_Field13:
			that1Type = 12
		case *SampleOneOf_Field14:
			that1Type = 13
		case *SampleOneOf_Field15:
			that1Type = 14
		case *SampleOneOf_SubMessage:
			that1Type = 15
		default:
			panic(fmt.Sprintf("compare: unexpected type %T in oneof", that1.TestOneof))
		}
		if thisType == that1Type {
			if c := this.TestOneof.Compare(that1.TestOneof); c != 0 {
				return c
			}
		} else if thisType < that1Type {
			return -1
		} else if thisType > that1Type {
			return 1
		}
	}
	if c := bytes.Compare(this.XXX_unrecognized, that1.XXX_unrecognized); c != 0 {
		return c
	}
	return 0
}
func (this *SampleOneOf_Field1) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field1)
	if !ok {
		that2, ok := that.(SampleOneOf_Field1)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field1 != that1.Field1 {
		if this.Field1 < that1.Field1 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field2) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field2)
	if !ok {
		that2, ok := that.(SampleOneOf_Field2)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field2 != that1.Field2 {
		if this.Field2 < that1.Field2 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field3) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field3)
	if !ok {
		that2, ok := that.(SampleOneOf_Field3)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field3 != that1.Field3 {
		if this.Field3 < that1.Field3 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field4) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field4)
	if !ok {
		that2, ok := that.(SampleOneOf_Field4)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field4 != that1.Field4 {
		if this.Field4 < that1.Field4 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field5) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field5)
	if !ok {
		that2, ok := that.(SampleOneOf_Field5)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field5 != that1.Field5 {
		if this.Field5 < that1.Field5 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field6) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field6)
	if !ok {
		that2, ok := that.(SampleOneOf_Field6)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field6 != that1.Field6 {
		if this.Field6 < that1.Field6 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field7) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field7)
	if !ok {
		that2, ok := that.(SampleOneOf_Field7)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field7 != that1.Field7 {
		if this.Field7 < that1.Field7 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field8) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field8)
	if !ok {
		that2, ok := that.(SampleOneOf_Field8)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field8 != that1.Field8 {
		if this.Field8 < that1.Field8 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field9) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field9)
	if !ok {
		that2, ok := that.(SampleOneOf_Field9)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field9 != that1.Field9 {
		if this.Field9 < that1.Field9 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field10) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field10)
	if !ok {
		that2, ok := that.(SampleOneOf_Field10)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field10 != that1.Field10 {
		if this.Field10 < that1.Field10 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field11) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field11)
	if !ok {
		that2, ok := that.(SampleOneOf_Field11)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field11 != that1.Field11 {
		if this.Field11 < that1.Field11 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field12) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field12)
	if !ok {
		that2, ok := that.(SampleOneOf_Field12)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field12 != that1.Field12 {
		if this.Field12 < that1.Field12 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field13) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field13)
	if !ok {
		that2, ok := that.(SampleOneOf_Field13)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field13 != that1.Field13 {
		if !this.Field13 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field14) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field14)
	if !ok {
		that2, ok := that.(SampleOneOf_Field14)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if this.Field14 != that1.Field14 {
		if this.Field14 < that1.Field14 {
			return -1
		}
		return 1
	}
	return 0
}
func (this *SampleOneOf_Field15) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_Field15)
	if !ok {
		that2, ok := that.(SampleOneOf_Field15)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if c := bytes.Compare(this.Field15, that1.Field15); c != 0 {
		return c
	}
	return 0
}
func (this *SampleOneOf_SubMessage) Compare(that interface{}) int {
	if that == nil {
		if this == nil {
			return 0
		}
		return 1
	}

	that1, ok := that.(*SampleOneOf_SubMessage)
	if !ok {
		that2, ok := that.(SampleOneOf_SubMessage)
		if ok {
			that1 = &that2
		} else {
			return 1
		}
	}
	if that1 == nil {
		if this == nil {
			return 0
		}
		return 1
	} else if this == nil {
		return -1
	}
	if c := this.SubMessage.Compare(that1.SubMessage); c != 0 {
		return c
	}
	return 0
}
func (this *Subby) Description() (desc *github_com_cosmos_gogoproto_protoc_gen_gogo_descriptor.FileDescriptorSet) {
	return OneDescription()
}
func (this *SampleOneOf) Description() (desc *github_com_cosmos_gogoproto_protoc_gen_gogo_descriptor.FileDescriptorSet) {
	return OneDescription()
}
func OneDescription() (desc *github_com_cosmos_gogoproto_protoc_gen_gogo_descriptor.FileDescriptorSet) {
	d := &github_com_cosmos_gogoproto_protoc_gen_gogo_descriptor.FileDescriptorSet{}
	var gzipped = []byte{
		// 4257 bytes of a gzipped FileDescriptorSet
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x5b, 0x6b, 0x6c, 0x23, 0xd7,
		0x75, 0x16, 0x9f, 0x22, 0x0f, 0x29, 0x6a, 0x34, 0x92, 0x77, 0xb9, 0x72, 0xcc, 0xdd, 0xa5, 0x1f,
		0x2b, 0xdb, 0x31, 0x65, 0x6b, 0x57, 0xfb, 0xe0, 0x36, 0x71, 0x29, 0x89, 0xab, 0x95, 0x2a, 0x89,
		0xca, 0x50, 0x8a, 0x1f, 0x45, 0x31, 0x18, 0x0e, 0xaf, 0xa8, 0xd9, 0x1d, 0xce, 0x4c, 0x66, 0x86,
		0xbb, 0xd6, 0xa2, 0x28, 0xb6, 0x70, 0x1f, 0x08, 0x8a, 0x3e, 0x92, 0x16, 0x68, 0xe3, 0x3a, 0x6e,
		0x93, 0xa2, 0xb5, 0x9b, 0xbe, 0x92, 0xb4, 0x4d, 0x93, 0xf6, 0x4f, 0xfa, 0xa3, 0xad, 0x7f, 0x15,
		0xc9, 0x8f, 0x02, 0xfd, 0xe9, 0x95, 0x0d, 0x34, 0x6d, 0xdd, 0xd6, 0x6d, 0xb6, 0x80, 0x01, 0xff,
		0x09, 0xee, 0x6b, 0x1e, 0x24, 0xb5, 0xc3, 0x0d, 0x60, 0xfb, 0x97, 0x38, 0xe7, 0x9c, 0xef, 0x9b,
		0x7b, 0xcf, 0x3d, 0xf7, 0x9e, 0x73, 0xef, 0x1d, 0xc1, 0x0f, 0x2f, 0xc3, 0xa9, 0x8e, 0x69, 0x76,
		0x74, 0x34, 0x6f, 0xd9, 0xa6, 0x6b, 0xb6, 0x7a, 0x7b, 0xf3, 0x6d, 0xe4, 0xa8, 0xb6, 0x66, 0xb9,
		0xa6, 0x5d, 0x21, 0x32, 0x71, 0x92, 0x5a, 0x54, 0xb8, 0x45, 0x79, 0x13, 0xa6, 0xae, 0x68, 0x3a,
		0x5a, 0xf1, 0x0c, 0x9b, 0xc8, 0x15, 0x2f, 0x42, 0x72, 0x4f, 0xd3, 0x51, 0x31, 0x76, 0x2a, 0x31,
		0x97, 0x5b, 0x78, 0xa4, 0xd2, 0x07, 0xaa, 0x84, 0x11, 0xdb, 0x58, 0x2c, 0x11, 0x44, 0xf9, 0x9d,
		0x24, 0x4c, 0x0f, 0xd1, 0x8a, 0x22, 0x24, 0x0d, 0xa5, 0x8b, 0x19, 0x63, 0x73, 0x59, 0x89, 0xfc,
		0x16, 0x8b, 0x30, 0x6e, 0x29, 0xea, 0x75, 0xa5, 0x83, 0x8a, 0x71, 0x22, 0xe6, 0x8f, 0x62, 0x09,
		0xa0, 0x8d, 0x2c, 0x64, 0xb4, 0x91, 0xa1, 0x1e, 0x14, 0x13, 0xa7, 0x12, 0x73, 0x59, 0x29, 0x20,
		0x11, 0x9f, 0x84, 0x29, 0xab, 0xd7, 0xd2, 0x35, 0x55, 0x0e, 0x98, 0xc1, 0xa9, 0xc4, 0x5c, 0x4a,
		0x12, 0xa8, 0x62, 0xc5, 0x37, 0x3e, 0x03, 0x93, 0x37, 0x91, 0x72, 0x3d, 0x68, 0x9a, 0x23, 0xa6,
		0x05, 0x2c, 0x0e, 0x18, 0x2e, 0x43, 0xbe, 0x8b, 0x1c, 0x47, 0xe9, 0x20, 0xd9, 0x3d, 0xb0, 0x50,
		0x31, 0x49, 0x7a, 0x7f, 0x6a, 0xa0, 0xf7, 0xfd, 0x3d, 0xcf, 0x31, 0xd4, 0xce, 0x81, 0x85, 0xc4,
		0x1a, 0x64, 0x91, 0xd1, 0xeb, 0x52, 0x86, 0xd4, 0x11, 0xfe, 0xab, 0x1b, 0xbd, 0x6e, 0x3f, 0x4b,
		0x06, 0xc3, 0x18, 0xc5, 0xb8, 0x83, 0xec, 0x1b, 0x9a, 0x8a, 0x8a, 0x69, 0x42, 0x70, 0x66, 0x80,
		0xa0, 0x49, 0xf5, 0xfd, 0x1c, 0x1c, 0x27, 0x2e, 0x43, 0x16, 0xbd, 0xe4, 0x22, 0xc3, 0xd1, 0x4c,
		0xa3, 0x38, 0x4e, 0x48, 0x1e, 0x1d, 0x32, 0x8a, 0x48, 0x6f, 0xf7, 0x53, 0xf8, 0x38, 0xf1, 0x3c,
		0x8c, 0x9b, 0x96, 0xab, 0x99, 0x86, 0x53, 0xcc, 0x9c, 0x8a, 0xcd, 0xe5, 0x16, 0x3e, 0x31, 0x34,
		0x10, 0x1a, 0xd4, 0x46, 0xe2, 0xc6, 0xe2, 0x1a, 0x08, 0x8e, 0xd9, 0xb3, 0x55, 0x24, 0xab, 0x66,
		0x1b, 0xc9, 0x9a, 0xb1, 0x67, 0x16, 0xb3, 0x84, 0xe0, 0xe4, 0x60, 0x47, 0x88, 0xe1, 0xb2, 0xd9,
		0x46, 0x6b, 0xc6, 0x9e, 0x29, 0x15, 0x9c, 0xd0, 0xb3, 0x78, 0x0c, 0xd2, 0xce, 0x81, 0xe1, 0x2a,
		0x2f, 0x15, 0xf3, 0x24, 0x42, 0xd8, 0x53, 0xf9, 0x3b, 0x69, 0x98, 0x1c, 0x25, 0xc4, 0x2e, 0x43,
		0x6a, 0x0f, 0xf7, 0xb2, 0x18, 0xbf, 0x1f, 0x1f, 0x50, 0x4c, 0xd8, 0x89, 0xe9, 0x1f, 0xd3, 0x89,
		0x35, 0xc8, 0x19, 0xc8, 0x71, 0x51, 0x9b, 0x46, 0x44, 0x62, 0xc4, 0x98, 0x02, 0x0a, 0x1a, 0x0c,
		0xa9, 0xe4, 0x8f, 0x15, 0x52, 0xcf, 0xc3, 0xa4, 0xd7, 0x24, 0xd9, 0x56, 0x8c, 0x0e, 0x8f, 0xcd,
		0xf9, 0xa8, 0x96, 0x54, 0xea, 0x1c, 0x27, 0x61, 0x98, 0x54, 0x40, 0xa1, 0x67, 0x71, 0x05, 0xc0,
		0x34, 0x90, 0xb9, 0x27, 0xb7, 0x91, 0xaa, 0x17, 0x33, 0x47, 0x78, 0xa9, 0x81, 0x4d, 0x06, 0xbc,
		0x64, 0x52, 0xa9, 0xaa, 0x8b, 0x97, 0xfc, 0x50, 0x1b, 0x3f, 0x22, 0x52, 0x36, 0xe9, 0x24, 0x1b,
		0x88, 0xb6, 0x5d, 0x28, 0xd8, 0x08, 0xc7, 0x3d, 0x6a, 0xb3, 0x9e, 0x65, 0x49, 0x23, 0x2a, 0x91,
		0x3d, 0x93, 0x18, 0x8c, 0x76, 0x6c, 0xc2, 0x0e, 0x3e, 0x8a, 0x0f, 0x83, 0x27, 0x90, 0x49, 0x58,
		0x01, 0x59, 0x85, 0xf2, 0x5c, 0xb8, 0xa5, 0x74, 0xd1, 0xec, 0x2d, 0x28, 0x84, 0xdd, 0x23, 0xce,
		0x40, 0xca, 0x71, 0x15, 0xdb, 0x25, 0x51, 0x98, 0x92, 0xe8, 0x83, 0x28, 0x40, 0x02, 0x19, 0x6d,
		0xb2, 0xca, 0xa5, 0x24, 0xfc, 0x53, 0xfc, 0x49, 0xbf, 0xc3, 0x09, 0xd2, 0xe1, 0xc7, 0x06, 0x47,
		0x34, 0xc4, 0xdc, 0xdf, 0xef, 0xd9, 0x0b, 0x30, 0x11, 0xea, 0xc0, 0xa8, 0xaf, 0x2e, 0xff, 0x2c,
		0x3c, 0x30, 0x94, 0x5a, 0x7c, 0x1e, 0x66, 0x7a, 0x86, 0x66, 0xb8, 0xc8, 0xb6, 0x6c, 0x84, 0x23,
		0x96, 0xbe, 0xaa, 0xf8, 0x6f, 0xe3, 0x47, 0xc4, 0xdc, 0x6e, 0xd0, 0x9a, 0xb2, 0x48, 0xd3, 0xbd,
		0x41, 0xe1, 0x13, 0xd9, 0xcc, 0x0f, 0xc6, 0x85, 0xdb, 0xb7, 0x6f, 0xdf, 0x8e, 0x97, 0xff, 0x3e,
		0x0d, 0x33, 0xc3, 0xe6, 0xcc, 0xd0, 0xe9, 0x7b, 0x0c, 0xd2, 0x46, 0xaf, 0xdb, 0x42, 0x36, 0x71,
		0x52, 0x4a, 0x62, 0x4f, 0x62, 0x0d, 0x52, 0xba, 0xd2, 0x42, 0x7a, 0x31, 0x79, 0x2a, 0x36, 0x57,
		0x58, 0x78, 0x72, 0xa4, 0x59, 0x59, 0xd9, 0xc0, 0x10, 0x89, 0x22, 0xc5, 0x4f, 0x43, 0x92, 0x2d,
		0xd1, 0x98, 0xe1, 0x89, 0xd1, 0x18, 0xf0, 0x5c, 0x92, 0x08, 0x4e, 0x7c, 0x10, 0xb2, 0xf8, 0x2f,
		0x8d, 0x8d, 0x34, 0x69, 0x73, 0x06, 0x0b, 0x70, 0x5c, 0x88, 0xb3, 0x90, 0x21, 0xd3, 0xa4, 0x8d,
		0x78, 0x6a, 0xf3, 0x9e, 0x71, 0x60, 0xb5, 0xd1, 0x9e, 0xd2, 0xd3, 0x5d, 0xf9, 0x86, 0xa2, 0xf7,
		0x10, 0x09, 0xf8, 0xac, 0x94, 0x67, 0xc2, 0xcf, 0x62, 0x99, 0x78, 0x12, 0x72, 0x74, 0x56, 0x69,
		0x46, 0x1b, 0xbd, 0x44, 0x56, 0xcf, 0x94, 0x44, 0x27, 0xda, 0x1a, 0x96, 0xe0, 0xd7, 0x5f, 0x73,
		0x4c, 0x83, 0x87, 0x26, 0x79, 0x05, 0x16, 0x90, 0xd7, 0x5f, 0xe8, 0x5f, 0xb8, 0x1f, 0x1a, 0xde,
		0xbd, 0x81, 0xb9, 0x74, 0x06, 0x26, 0x89, 0xc5, 0x59, 0x36, 0xf4, 0x8a, 0x5e, 0x9c, 0x3a, 0x15,
		0x9b, 0xcb, 0x48, 0x05, 0x2a, 0x6e, 0x30, 0x69, 0xf9, 0x5b, 0x71, 0x48, 0x92, 0x85, 0x65, 0x12,
		0x72, 0x3b, 0x2f, 0x6c, 0xd7, 0xe5, 0x95, 0xc6, 0xee, 0xd2, 0x46, 0x5d, 0x88, 0x89, 0x05, 0x00,
		0x22, 0xb8, 0xb2, 0xd1, 0xa8, 0xed, 0x08, 0x71, 0xef, 0x79, 0x6d, 0x6b, 0xe7, 0xfc, 0x39, 0x21,
		0xe1, 0x01, 0x76, 0xa9, 0x20, 0x19, 0x34, 0x38, 0xbb, 0x20, 0xa4, 0x44, 0x01, 0xf2, 0x94, 0x60,
		0xed, 0xf9, 0xfa, 0xca, 0xf9, 0x73, 0x42, 0x3a, 0x2c, 0x39, 0xbb, 0x20, 0x8c, 0x8b, 0x13, 0x90,
		0x25, 0x92, 0xa5, 0x46, 0x63, 0x43, 0xc8, 0x78, 0x9c, 0xcd, 0x1d, 0x69, 0x6d, 0x6b, 0x55, 0xc8,
		0x7a, 0x9c, 0xab, 0x52, 0x63, 0x77, 0x5b, 0x00, 0x8f, 0x61, 0xb3, 0xde, 0x6c, 0xd6, 0x56, 0xeb,
		0x42, 0xce, 0xb3, 0x58, 0x7a, 0x61, 0xa7, 0xde, 0x14, 0xf2, 0xa1, 0x66, 0x9d, 0x5d, 0x10, 0x26,
		0xbc, 0x57, 0xd4, 0xb7, 0x76, 0x37, 0x85, 0x82, 0x38, 0x05, 0x13, 0xf4, 0x15, 0xbc, 0x11, 0x93,
		0x7d, 0xa2, 0xf3, 0xe7, 0x04, 0xc1, 0x6f, 0x08, 0x65, 0x99, 0x0a, 0x09, 0xce, 0x9f, 0x13, 0xc4,
		0xf2, 0x32, 0xa4, 0x48, 0x18, 0x8a, 0x22, 0x14, 0x36, 0x6a, 0x4b, 0xf5, 0x0d, 0xb9, 0xb1, 0xbd,
		0xb3, 0xd6, 0xd8, 0xaa, 0x6d, 0x08, 0x31, 0x5f, 0x26, 0xd5, 0x3f, 0xb3, 0xbb, 0x26, 0xd5, 0x57,
		0x84, 0x78, 0x50, 0xb6, 0x5d, 0xaf, 0xed, 0xd4, 0x57, 0x84, 0x44, 0x59, 0x85, 0x99, 0x61, 0x0b,
		0xea, 0xd0, 0x29, 0x14, 0x88, 0x85, 0xf8, 0x11, 0xb1, 0x40, 0xb8, 0xfa, 0x63, 0xa1, 0xfc, 0x76,
		0x1c, 0xa6, 0x87, 0x24, 0x95, 0xa1, 0x2f, 0x79, 0x16, 0x52, 0x34, 0x96, 0x69, 0x9a, 0x7d, 0x7c,
		0x68, 0x76, 0x22, 0x91, 0x3d, 0x90, 0x6a, 0x09, 0x2e, 0x58, 0x6a, 0x24, 0x8e, 0x28, 0x35, 0x30,
		0xc5, 0x40, 0xc0, 0xfe, 0xcc, 0xc0, 0xe2, 0x4f, 0xf3, 0xe3, 0xf9, 0x51, 0xf2, 0x23, 0x91, 0xdd,
		0x5f, 0x12, 0x48, 0x0d, 0x49, 0x02, 0x97, 0x61, 0x6a, 0x80, 0x68, 0xe4, 0xc5, 0xf8, 0xe5, 0x18,
		0x14, 0x8f, 0x72, 0x4e, 0xc4, 0x92, 0x18, 0x0f, 0x2d, 0x89, 0x97, 0xfb, 0x3d, 0x78, 0xfa, 0xe8,
		0x41, 0x18, 0x18, 0xeb, 0xd7, 0x63, 0x70, 0x6c, 0x78, 0x49, 0x39, 0xb4, 0x0d, 0x9f, 0x86, 0x74,
		0x17, 0xb9, 0xfb, 0x26, 0x2f, 0xab, 0x1e, 0x1b, 0x92, 0xac, 0xb1, 0xba, 0x7f, 0xb0, 0x19, 0x2a,
		0x98, 0xed, 0x13, 0x47, 0xd5, 0x85, 0xb4, 0x35, 0x03, 0x2d, 0xfd, 0x7c, 0x1c, 0x1e, 0x18, 0x4a,
		0x3e, 0xb4, 0xa1, 0x0f, 0x01, 0x68, 0x86, 0xd5, 0x73, 0x69, 0xe9, 0x44, 0x57, 0xe2, 0x2c, 0x91,
		0x90, 0xc5, 0x0b, 0xaf, 0xb2, 0x3d, 0xd7, 0xd3, 0x27, 0x88, 0x1e, 0xa8, 0x88, 0x18, 0x5c, 0xf4,
		0x1b, 0x9a, 0x24, 0x0d, 0x2d, 0x1d, 0xd1, 0xd3, 0x81, 0xc0, 0x7c, 0x1a, 0x04, 0x55, 0xd7, 0x90,
		0xe1, 0xca, 0x8e, 0x6b, 0x23, 0xa5, 0xab, 0x19, 0x1d, 0x92, 0x6a, 0x32, 0xd5, 0xd4, 0x9e, 0xa2,
		0x3b, 0x48, 0x9a, 0xa4, 0xea, 0x26, 0xd7, 0x62, 0x04, 0x09, 0x20, 0x3b, 0x80, 0x48, 0x87, 0x10,
		0x54, 0xed, 0x21, 0xca, 0x5f, 0xc8, 0x42, 0x2e, 0x50, 0x80, 0x8b, 0xa7, 0x21, 0x7f, 0x4d, 0xb9,
		0xa1, 0xc8, 0x7c, 0x53, 0x45, 0x3d, 0x91, 0xc3, 0xb2, 0x6d, 0xb6, 0xb1, 0x7a, 0x1a, 0x66, 0x88,
		0x89, 0xd9, 0x73, 0x91, 0x2d, 0xab, 0xba, 0xe2, 0x38, 0xc4, 0x69, 0x19, 0x62, 0x2a, 0x62, 0x5d,
		0x03, 0xab, 0x96, 0xb9, 0x46, 0x5c, 0x84, 0x69, 0x82, 0xe8, 0xf6, 0x74, 0x57, 0xb3, 0x74, 0x24,
		0xe3, 0x6d, 0x9e, 0x43, 0x52, 0x8e, 0xd7, 0xb2, 0x29, 0x6c, 0xb1, 0xc9, 0x0c, 0x70, 0x8b, 0x1c,
		0x71, 0x05, 0x1e, 0x22, 0xb0, 0x0e, 0x32, 0x90, 0xad, 0xb8, 0x48, 0x46, 0x9f, 0xeb, 0x29, 0xba,
		0x23, 0x2b, 0x46, 0x5b, 0xde, 0x57, 0x9c, 0xfd, 0xe2, 0x0c, 0x26, 0x58, 0x8a, 0x17, 0x63, 0xd2,
		0x09, 0x6c, 0xb8, 0xca, 0xec, 0xea, 0xc4, 0xac, 0x66, 0xb4, 0xaf, 0x2a, 0xce, 0xbe, 0x58, 0x85,
		0x63, 0x84, 0xc5, 0x71, 0x6d, 0xcd, 0xe8, 0xc8, 0xea, 0x3e, 0x52, 0xaf, 0xcb, 0x3d, 0x77, 0xef,
		0x62, 0xf1, 0xc1, 0xe0, 0xfb, 0x49, 0x0b, 0x9b, 0xc4, 0x66, 0x19, 0x9b, 0xec, 0xba, 0x7b, 0x17,
		0xc5, 0x26, 0xe4, 0xf1, 0x60, 0x74, 0xb5, 0x5b, 0x48, 0xde, 0x33, 0x6d, 0x92, 0x43, 0x0b, 0x43,
		0x96, 0xa6, 0x80, 0x07, 0x2b, 0x0d, 0x06, 0xd8, 0x34, 0xdb, 0xa8, 0x9a, 0x6a, 0x6e, 0xd7, 0xeb,
		0x2b, 0x52, 0x8e, 0xb3, 0x5c, 0x31, 0x6d, 0x1c, 0x50, 0x1d, 0xd3, 0x73, 0x70, 0x8e, 0x06, 0x54,
		0xc7, 0xe4, 0xee, 0x5d, 0x84, 0x69, 0x55, 0xa5, 0x7d, 0xd6, 0x54, 0x99, 0x6d, 0xc6, 0x9c, 0xa2,
		0x10, 0x72, 0x96, 0xaa, 0xae, 0x52, 0x03, 0x16, 0xe3, 0x8e, 0x78, 0x09, 0x1e, 0xf0, 0x9d, 0x15,
		0x04, 0x4e, 0x0d, 0xf4, 0xb2, 0x1f, 0xba, 0x08, 0xd3, 0xd6, 0xc1, 0x20, 0x50, 0x0c, 0xbd, 0xd1,
		0x3a, 0xe8, 0x87, 0x5d, 0x80, 0x19, 0x6b, 0xdf, 0x1a, 0xc4, 0x3d, 0x11, 0xc4, 0x89, 0xd6, 0xbe,
		0xd5, 0x0f, 0x7c, 0x94, 0xec, 0xcc, 0x6d, 0xa4, 0x2a, 0x2e, 0x6a, 0x17, 0x8f, 0x07, 0xcd, 0x03,
		0x0a, 0xb1, 0x02, 0x82, 0xaa, 0xca, 0xc8, 0x50, 0x5a, 0x3a, 0x92, 0x15, 0x1b, 0x19, 0x8a, 0x53,
		0x3c, 0x49, 0x8c, 0x93, 0xae, 0xdd, 0x43, 0x52, 0x41, 0x55, 0xeb, 0x44, 0x59, 0x23, 0x3a, 0xf1,
		0x09, 0x98, 0x32, 0x5b, 0xd7, 0x54, 0x1a, 0x91, 0xb2, 0x65, 0xa3, 0x3d, 0xed, 0xa5, 0xe2, 0x23,
		0xc4, 0xbd, 0x93, 0x58, 0x41, 0xe2, 0x71, 0x9b, 0x88, 0xc5, 0xc7, 0x41, 0x50, 0x9d, 0x7d, 0xc5,
		0xb6, 0xc8, 0x92, 0xec, 0x58, 0x8a, 0x8a, 0x8a, 0x8f, 0x52, 0x53, 0x2a, 0xdf, 0xe2, 0x62, 0x3c,
		0x23, 0x9c, 0x9b, 0xda, 0x9e, 0xcb, 0x19, 0xcf, 0xd0, 0x19, 0x41, 0x64, 0x8c, 0x6d, 0x0e, 0x04,
		0xec, 0x89, 0xd0, 0x8b, 0xe7, 0x88, 0x59, 0xc1, 0xda, 0xb7, 0x82, 0xef, 0x7d, 0x18, 0x26, 0xb0,
		0xa5, 0xff, 0xd2, 0xc7, 0x69, 0xe1, 0x66, 0xed, 0x07, 0xde, 0x78, 0x0e, 0x8e, 0x61, 0xa3, 0x2e,
		0x72, 0x95, 0xb6, 0xe2, 0x2a, 0x01, 0xeb, 0x4f, 0x12, 0x6b, 0xec, 0xf6, 0x4d, 0xa6, 0x0c, 0xb5,
		0xd3, 0xee, 0xb5, 0x0e, 0xbc, 0xc0, 0x7a, 0x8a, 0xb6, 0x13, 0xcb, 0x78, 0x68, 0x7d, 0x68, 0xc5,
		0x79, 0xb9, 0x0a, 0xf9, 0x60, 0xdc, 0x8b, 0x59, 0xa0, 0x91, 0x2f, 0xc4, 0x70, 0x11, 0xb4, 0xdc,
		0x58, 0xc1, 0xe5, 0xcb, 0x8b, 0x75, 0x21, 0x8e, 0xcb, 0xa8, 0x8d, 0xb5, 0x9d, 0xba, 0x2c, 0xed,
		0x6e, 0xed, 0xac, 0x6d, 0xd6, 0x85, 0x44, 0xa0, 0xb0, 0x5f, 0x4f, 0x66, 0x1e, 0x13, 0xce, 0xe0,
		0xaa, 0xa1, 0x10, 0xde, 0xa9, 0x89, 0x3f, 0x01, 0xc7, 0xf9, 0xb1, 0x8a, 0x83, 0x5c, 0xf9, 0xa6,
		0x66, 0x93, 0x09, 0xd9, 0x55, 0x68, 0x72, 0xf4, 0xe2, 0x67, 0x86, 0x59, 0x35, 0x91, 0xfb, 0x9c,
		0x66, 0xe3, 0xe9, 0xd6, 0x55, 0x5c, 0x71, 0x03, 0x4e, 0x1a, 0xa6, 0xec, 0xb8, 0x8a, 0xd1, 0x56,
		0xec, 0xb6, 0xec, 0x1f, 0x68, 0xc9, 0x8a, 0xaa, 0x22, 0xc7, 0x31, 0x69, 0x22, 0xf4, 0x58, 0x3e,
		0x61, 0x98, 0x4d, 0x66, 0xec, 0x67, 0x88, 0x1a, 0x33, 0xed, 0x0b, 0xdf, 0xc4, 0x51, 0xe1, 0xfb,
		0x20, 0x64, 0xbb, 0x8a, 0x25, 0x23, 0xc3, 0xb5, 0x0f, 0x48, 0x7d, 0x9e, 0x91, 0x32, 0x5d, 0xc5,
		0xaa, 0xe3, 0xe7, 0x8f, 0x64, 0x9b, 0xb4, 0x9e, 0xcc, 0x24, 0x85, 0xd4, 0x7a, 0x32, 0x93, 0x12,
		0xd2, 0xeb, 0xc9, 0x4c, 0x5a, 0x18, 0x5f, 0x4f, 0x66, 0x32, 0x42, 0x76, 0x3d, 0x99, 0xc9, 0x0a,
		0x50, 0xfe, 0x62, 0x12, 0xf2, 0xc1, 0x0a, 0x1e, 0x6f, 0x88, 0x54, 0x92, 0xc3, 0x62, 0x64, 0x95,
		0x7b, 0xf8, 0x9e, 0xf5, 0x7e, 0x65, 0x19, 0x27, 0xb7, 0x6a, 0x9a, 0x96, 0xcb, 0x12, 0x45, 0xe2,
		0xc2, 0x02, 0x87, 0x1f, 0xa2, 0xe5, 0x49, 0x46, 0x62, 0x4f, 0xe2, 0x2a, 0xa4, 0xaf, 0x39, 0x84,
		0x3b, 0x4d, 0xb8, 0x1f, 0xb9, 0x37, 0xf7, 0x7a, 0x93, 0x90, 0x67, 0xd7, 0x9b, 0xf2, 0x56, 0x43,
		0xda, 0xac, 0x6d, 0x48, 0x0c, 0x2e, 0x9e, 0x80, 0xa4, 0xae, 0xdc, 0x3a, 0x08, 0xa7, 0x41, 0x22,
		0x12, 0x2b, 0x30, 0xd9, 0x33, 0x6e, 0x20, 0x5b, 0xdb, 0xd3, 0x50, 0x5b, 0x26, 0x56, 0x93, 0x41,
		0xab, 0x82, 0xaf, 0xdd, 0xc0, 0xf6, 0x23, 0x0e, 0xe3, 0x09, 0x48, 0xde, 0x44, 0xca, 0xf5, 0x70,
		0xb2, 0x22, 0xa2, 0x0f, 0x71, 0x3a, 0xcd, 0x43, 0x8a, 0xf8, 0x57, 0x04, 0x60, 0x1e, 0x16, 0xc6,
		0xc4, 0x0c, 0x24, 0x97, 0x1b, 0x12, 0x9e, 0x52, 0x02, 0xe4, 0xa9, 0x54, 0xde, 0x5e, 0xab, 0x2f,
		0xd7, 0x85, 0x78, 0x79, 0x11, 0xd2, 0xd4, 0x69, 0x78, 0xba, 0x79, 0x6e, 0x13, 0xc6, 0xd8, 0x23,
		0xe3, 0x88, 0x71, 0xed, 0xee, 0xe6, 0x52, 0x5d, 0x12, 0xe2, 0x03, 0xc1, 0x52, 0x76, 0x20, 0x1f,
		0xac, 0xe4, 0x3f, 0x9a, 0xed, 0xfc, 0x77, 0x63, 0x90, 0x0b, 0x54, 0xe6, 0xb8, 0xa4, 0x52, 0x74,
		0xdd, 0xbc, 0x29, 0x2b, 0xba, 0xa6, 0x38, 0x2c, 0x94, 0x80, 0x88, 0x6a, 0x58, 0x32, 0xea, 0xd0,
		0x7d, 0x44, 0x93, 0x2c, 0x25, 0xa4, 0xcb, 0xaf, 0xc5, 0x40, 0xe8, 0x2f, 0x8d, 0xfb, 0x9a, 0x19,
		0xfb, 0x38, 0x9b, 0x59, 0x7e, 0x35, 0x06, 0x85, 0x70, 0x3d, 0xdc, 0xd7, 0xbc, 0xd3, 0x1f, 0x6b,
		0xf3, 0xde, 0x8a, 0xc3, 0x44, 0xa8, 0x0a, 0x1e, 0xb5, 0x75, 0x9f, 0x83, 0x29, 0xad, 0x8d, 0xba,
		0x96, 0xe9, 0x22, 0x43, 0x3d, 0x90, 0x75, 0x74, 0x03, 0xe9, 0xc5, 0x32, 0x59, 0x64, 0xe6, 0xef,
		0x5d, 0x67, 0x57, 0xd6, 0x7c, 0xdc, 0x06, 0x86, 0x55, 0xa7, 0xd7, 0x56, 0xea, 0x9b, 0xdb, 0x8d,
		0x9d, 0xfa, 0xd6, 0xf2, 0x0b, 0xf2, 0xee, 0xd6, 0x4f, 0x6d, 0x35, 0x9e, 0xdb, 0x92, 0x04, 0xad,
		0xcf, 0xec, 0x43, 0x9c, 0xf6, 0xdb, 0x20, 0xf4, 0x37, 0x4a, 0x3c, 0x0e, 0xc3, 0x9a, 0x25, 0x8c,
		0x89, 0xd3, 0x30, 0xb9, 0xd5, 0x90, 0x9b, 0x6b, 0x2b, 0x75, 0xb9, 0x7e, 0xe5, 0x4a, 0x7d, 0x79,
		0xa7, 0x49, 0x4f, 0x4e, 0x3c, 0xeb, 0x9d, 0xd0, 0x04, 0x2f, 0xbf, 0x92, 0x80, 0xe9, 0x21, 0x2d,
		0x11, 0x6b, 0x6c, 0xcf, 0x43, 0xb7, 0x61, 0x4f, 0x8d, 0xd2, 0xfa, 0x0a, 0xae, 0x3a, 0xb6, 0x15,
		0xdb, 0x65, 0x5b, 0xa4, 0xc7, 0x01, 0x7b, 0xc9, 0x70, 0xf1, 0xe2, 0x6a, 0xb3, 0x13, 0x29, 0xba,
		0x11, 0x9a, 0xf4, 0xe5, 0xf4, 0x50, 0xea, 0x93, 0x20, 0x5a, 0xa6, 0xa3, 0xb9, 0xda, 0x0d, 0x24,
		0x6b, 0x06, 0x3f, 0xbe, 0xc2, 0x1b, 0xa3, 0xa4, 0x24, 0x70, 0xcd, 0x9a, 0xe1, 0x7a, 0xd6, 0x06,
		0xea, 0x28, 0x7d, 0xd6, 0x78, 0xf1, 0x4f, 0x48, 0x02, 0xd7, 0x78, 0xd6, 0xa7, 0x21, 0xdf, 0x36,
		0x7b, 0xb8, 0x5a, 0xa4, 0x76, 0x38, 0xd7, 0xc4, 0xa4, 0x1c, 0x95, 0x79, 0x26, 0x6c, 0x1f, 0xe0,
		0x9f, 0x9b, 0xe5, 0xa5, 0x1c, 0x95, 0x51, 0x93, 0x33, 0x30, 0xa9, 0x74, 0x3a, 0x36, 0x26, 0xe7,
		0x44, 0x74, 0x67, 0x53, 0xf0, 0xc4, 0xc4, 0x70, 0x76, 0x1d, 0x32, 0xdc, 0x0f, 0x38, 0xd9, 0x63,
		0x4f, 0xc8, 0x16, 0xdd, 0xae, 0xc7, 0xe7, 0xb2, 0x52, 0xc6, 0xe0, 0xca, 0xd3, 0x90, 0xd7, 0x1c,
		0xd9, 0xbf, 0x06, 0x88, 0x9f, 0x8a, 0xcf, 0x65, 0xa4, 0x9c, 0xe6, 0x78, 0x47, 0xa8, 0xe5, 0xd7,
		0xe3, 0x50, 0x08, 0x5f, 0x63, 0x88, 0x2b, 0x90, 0xd1, 0x4d, 0x55, 0x21, 0xa1, 0x45, 0xef, 0xd0,
		0xe6, 0x22, 0x6e, 0x3e, 0x2a, 0x1b, 0xcc, 0x5e, 0xf2, 0x90, 0xb3, 0xff, 0x1c, 0x83, 0x0c, 0x17,
		0x8b, 0xc7, 0x20, 0x69, 0x29, 0xee, 0x3e, 0xa1, 0x4b, 0x2d, 0xc5, 0x85, 0x98, 0x44, 0x9e, 0xb1,
		0xdc, 0xb1, 0x14, 0x83, 0x84, 0x00, 0x93, 0xe3, 0x67, 0x3c, 0xae, 0x3a, 0x52, 0xda, 0x64, 0xdb,
		0x64, 0x76, 0xbb, 0xc8, 0x70, 0x1d, 0x3e, 0xae, 0x4c, 0xbe, 0xcc, 0xc4, 0xe2, 0x93, 0x30, 0xe5,
		0xda, 0x8a, 0xa6, 0x87, 0x6c, 0x93, 0xc4, 0x56, 0xe0, 0x0a, 0xcf, 0xb8, 0x0a, 0x27, 0x38, 0x6f,
		0x1b, 0xb9, 0x8a, 0xba, 0x8f, 0xda, 0x3e, 0x28, 0x4d, 0x8e, 0x47, 0x8e, 0x33, 0x83, 0x15, 0xa6,
		0xe7, 0xd8, 0xf2, 0xf7, 0x63, 0x30, 0xc5, 0x37, 0x7a, 0x6d, 0xcf, 0x59, 0x9b, 0x00, 0x8a, 0x61,
		0x98, 0x6e, 0xd0, 0x5d, 0x83, 0xa1, 0x3c, 0x80, 0xab, 0xd4, 0x3c, 0x90, 0x14, 0x20, 0x98, 0xed,
		0x02, 0xf8, 0x9a, 0x23, 0xdd, 0x76, 0x12, 0x72, 0xec, 0x8e, 0x8a, 0x5c, 0x74, 0xd2, 0xa3, 0x01,
		0xa0, 0x22, 0xbc, 0x23, 0x14, 0x67, 0x20, 0xd5, 0x42, 0x1d, 0xcd, 0x60, 0x27, 0xcf, 0xf4, 0x81,
		0x1f, 0xe0, 0x24, 0xbd, 0x03, 0x9c, 0xa5, 0x9f, 0x83, 0x69, 0xd5, 0xec, 0xf6, 0x37, 0x77, 0x49,
		0xe8, 0x3b, 0x9e, 0x70, 0xae, 0xc6, 0x5e, 0x7c, 0x8a, 0x19, 0x75, 0x4c, 0x5d, 0x31, 0x3a, 0x15,
		0xd3, 0xee, 0xf8, 0x17, 0xb5, 0xb8, 0x42, 0x72, 0x02, 0xd7, 0xb5, 0x56, 0xeb, 0xfd, 0x58, 0xec,
		0xab, 0xf1, 0xc4, 0xea, 0xf6, 0xd2, 0xd7, 0xe2, 0xb3, 0xab, 0x14, 0xb8, 0xcd, 0x9d, 0x21, 0xa1,
		0x3d, 0x1d, 0xa9, 0xb8, 0x83, 0xf0, 0x2f, 0x4f, 0xc2, 0x4c, 0xc7, 0xec, 0x98, 0x84, 0x69, 0x1e,
		0xff, 0x62, 0x37, 0xbd, 0x59, 0x4f, 0x3a, 0x1b, 0x79, 0x2d, 0x5c, 0xdd, 0x82, 0x69, 0x66, 0x2c,
		0x93, 0xab, 0x26, 0xba, 0x11, 0x12, 0xef, 0x79, 0x0a, 0x57, 0xfc, 0xc6, 0x3b, 0x24, 0x7d, 0x4b,
		0x53, 0x0c, 0x8a, 0x75, 0x74, 0xaf, 0x54, 0x95, 0xe0, 0x81, 0x10, 0x1f, 0x9d, 0xa4, 0xc8, 0x8e,
		0x60, 0xfc, 0x07, 0xc6, 0x38, 0x1d, 0x60, 0x6c, 0x32, 0x68, 0x75, 0x19, 0x26, 0xee, 0x87, 0xeb,
		0x1f, 0x19, 0x57, 0x1e, 0x05, 0x49, 0x56, 0x61, 0x92, 0x90, 0xa8, 0x3d, 0xc7, 0x35, 0xbb, 0x64,
		0x05, 0xbc, 0x37, 0xcd, 0x3f, 0xbd, 0x43, 0x67, 0x4d, 0x01, 0xc3, 0x96, 0x3d, 0x54, 0xb5, 0x0a,
		0xe4, 0x76, 0xad, 0x8d, 0x54, 0x3d, 0x82, 0xe1, 0x4d, 0xd6, 0x10, 0xcf, 0xbe, 0xfa, 0x59, 0x98,
		0xc1, 0xbf, 0xc9, 0x02, 0x15, 0x6c, 0x49, 0xf4, 0x91, 0x5d, 0xf1, 0xfb, 0x2f, 0xd3, 0x89, 0x39,
		0xed, 0x11, 0x04, 0xda, 0x14, 0x18, 0xc5, 0x0e, 0x72, 0x5d, 0x64, 0x3b, 0xb2, 0xa2, 0x0f, 0x6b,
		0x5e, 0xe0, 0xcc, 0xa3, 0xf8, 0xa5, 0x77, 0xc3, 0xa3, 0xb8, 0x4a, 0x91, 0x35, 0x5d, 0xaf, 0xee,
		0xc2, 0xf1, 0x21, 0x51, 0x31, 0x02, 0xe7, 0x2b, 0x8c, 0x73, 0x66, 0x20, 0x32, 0x30, 0xed, 0x36,
		0x70, 0xb9, 0x37, 0x96, 0x23, 0x70, 0xfe, 0x2e, 0xe3, 0x14, 0x19, 0x96, 0x0f, 0x29, 0x66, 0x5c,
		0x87, 0xa9, 0x1b, 0xc8, 0x6e, 0x99, 0x0e, 0x3b, 0x67, 0x1a, 0x81, 0xee, 0x55, 0x46, 0x37, 0xc9,
		0x80, 0xe4, 0xe0, 0x09, 0x73, 0x5d, 0x82, 0xcc, 0x9e, 0xa2, 0xa2, 0x11, 0x28, 0xbe, 0xcc, 0x28,
		0xc6, 0xb1, 0x3d, 0x86, 0xd6, 0x20, 0xdf, 0x31, 0x59, 0x8e, 0x8a, 0x86, 0xbf, 0xc6, 0xe0, 0x39,
		0x8e, 0x61, 0x14, 0x96, 0x69, 0xf5, 0x74, 0x9c, 0xc0, 0xa2, 0x29, 0x7e, 0x8f, 0x53, 0x70, 0x0c,
		0xa3, 0xb8, 0x0f, 0xb7, 0xfe, 0x3e, 0xa7, 0x70, 0x02, 0xfe, 0x7c, 0x16, 0x72, 0xa6, 0xa1, 0x1f,
		0x98, 0xc6, 0x28, 0x8d, 0xf8, 0x0a, 0x63, 0x00, 0x06, 0xc1, 0x04, 0x97, 0x21, 0x3b, 0xea, 0x40,
		0xfc, 0xe1, 0xbb, 0x7c, 0x7a, 0xf0, 0x11, 0x58, 0x85, 0x49, 0xbe, 0x40, 0x69, 0xa6, 0x31, 0x02,
		0xc5, 0x1f, 0x31, 0x8a, 0x42, 0x00, 0xc6, 0xba, 0xe1, 0x22, 0xc7, 0xed, 0xa0, 0x51, 0x48, 0x5e,
		0xe7, 0xdd, 0x60, 0x10, 0xe6, 0xca, 0x16, 0x32, 0xd4, 0xfd, 0xd1, 0x18, 0xde, 0xe0, 0xae, 0xe4,
		0x18, 0x4c, 0xb1, 0x0c, 0x13, 0x5d, 0xc5, 0x76, 0xf6, 0x15, 0x7d, 0xa4, 0xe1, 0xf8, 0x63, 0xc6,
		0x91, 0xf7, 0x40, 0xcc, 0x23, 0x3d, 0xe3, 0x7e, 0x68, 0xbe, 0xc6, 0x3d, 0x12, 0x80, 0xb1, 0xa9,
		0xe7, 0xb8, 0xe4, 0x50, 0xee, 0x7e, 0xd8, 0xfe, 0x84, 0x4f, 0x3d, 0x8a, 0xdd, 0x0c, 0x32, 0x5e,
		0x86, 0xac, 0xa3, 0xdd, 0x1a, 0x89, 0xe6, 0x4f, 0xf9, 0x48, 0x13, 0x00, 0x06, 0xbf, 0x00, 0x27,
		0x86, 0xa6, 0x89, 0x11, 0xc8, 0xfe, 0x8c, 0x91, 0x1d, 0x1b, 0x92, 0x2a, 0xd8, 0x92, 0x70, 0xbf,
		0x94, 0x7f, 0xce, 0x97, 0x04, 0xd4, 0xc7, 0xb5, 0x8d, 0x77, 0x0d, 0x8e, 0xb2, 0x77, 0x7f, 0x5e,
		0xfb, 0x0b, 0xee, 0x35, 0x8a, 0x0d, 0x79, 0x6d, 0x07, 0x8e, 0x31, 0xc6, 0xfb, 0x1b, 0xd7, 0xaf,
		0xf3, 0x85, 0x95, 0xa2, 0x77, 0xc3, 0xa3, 0xfb, 0xd3, 0x30, 0xeb, 0xb9, 0x93, 0x97, 0xa7, 0x8e,
		0xdc, 0x55, 0xac, 0x11, 0x98, 0xbf, 0xc1, 0x98, 0xf9, 0x8a, 0xef, 0xd5, 0xb7, 0xce, 0xa6, 0x62,
		0x61, 0xf2, 0xe7, 0xa1, 0xc8, 0xc9, 0x7b, 0x86, 0x8d, 0x54, 0xb3, 0x63, 0x68, 0xb7, 0x50, 0x7b,
		0x04, 0xea, 0x6f, 0xf6, 0x0d, 0xd5, 0x6e, 0x00, 0x8e, 0x99, 0xd7, 0x40, 0xf0, 0x6a, 0x15, 0x59,
		0xeb, 0x5a, 0xa6, 0xed, 0x46, 0x30, 0xfe, 0x25, 0x1f, 0x29, 0x0f, 0xb7, 0x46, 0x60, 0xd5, 0x3a,
		0xd0, 0x9b, 0xea, 0x51, 0x43, 0xf2, 0xaf, 0x18, 0xd1, 0x84, 0x8f, 0x62, 0x0b, 0x87, 0x6a, 0x76,
		0x2d, 0xc5, 0x1e, 0x65, 0xfd, 0xfb, 0x6b, 0xbe, 0x70, 0x30, 0x08, 0x5b, 0x38, 0x70, 0x45, 0x87,
		0xb3, 0xfd, 0x08, 0x0c, 0xdf, 0xe2, 0x0b, 0x07, 0xc7, 0x30, 0x0a, 0x5e, 0x30, 0x8c, 0x40, 0xf1,
		0x37, 0x9c, 0x82, 0x63, 0x30, 0xc5, 0x67, 0xfc, 0x44, 0x6b, 0xa3, 0x8e, 0xe6, 0xb8, 0x36, 0x2d,
		0x8a, 0xef, 0x4d, 0xf5, 0xed, 0x77, 0xc3, 0x45, 0x98, 0x14, 0x80, 0xe2, 0x95, 0x88, 0x1d, 0xd3,
		0x92, 0x3d, 0x53, 0x74, 0xc3, 0xbe, 0xc3, 0x57, 0xa2, 0x00, 0x0c, 0xb7, 0x2d, 0x50, 0x21, 0x62,
		0xb7, 0xab, 0x78, 0xa7, 0x30, 0x02, 0xdd, 0xdf, 0xf6, 0x35, 0xae, 0xc9, 0xb1, 0x98, 0x33, 0x50,
		0xff, 0xf4, 0x8c, 0xeb, 0xe8, 0x60, 0xa4, 0xe8, 0xfc, 0xbb, 0xbe, 0xfa, 0x67, 0x97, 0x22, 0xe9,
		0x1a, 0x32, 0xd9, 0x57, 0x4f, 0x89, 0x51, 0xdf, 0x25, 0x15, 0x7f, 0xfe, 0x2e, 0xeb, 0x6f, 0xb8,
		0x9c, 0xaa, 0x6e, 0xe0, 0x20, 0x0f, 0x17, 0x3d, 0xd1, 0x64, 0x2f, 0xdf, 0xf5, 0xe2, 0x3c, 0x54,
		0xf3, 0x54, 0xaf, 0xc0, 0x44, 0xa8, 0xe0, 0x89, 0xa6, 0xfa, 0x05, 0x46, 0x95, 0x0f, 0xd6, 0x3b,
		0xd5, 0x45, 0x48, 0xe2, 0xe2, 0x25, 0x1a, 0xfe, 0x8b, 0x0c, 0x4e, 0xcc, 0xab, 0x9f, 0x82, 0x0c,
		0x2f, 0x5a, 0xa2, 0xa1, 0xbf, 0xc4, 0xa0, 0x1e, 0x04, 0xc3, 0x79, 0xc1, 0x12, 0x0d, 0xff, 0x65,
		0x0e, 0xe7, 0x10, 0x0c, 0x1f, 0xdd, 0x85, 0xdf, 0xfd, 0x95, 0x24, 0x4b, 0x3a, 0xdc, 0x77, 0x97,
		0x61, 0x9c, 0x55, 0x2a, 0xd1, 0xe8, 0xcf, 0xb3, 0x97, 0x73, 0x44, 0xf5, 0x02, 0xa4, 0x46, 0x74,
		0xf8, 0xaf, 0x32, 0x28, 0xb5, 0xaf, 0x2e, 0x43, 0x2e, 0x50, 0x9d, 0x44, 0xc3, 0x7f, 0x8d, 0xc1,
		0x83, 0x28, 0xdc, 0x74, 0x56, 0x9d, 0x44, 0x13, 0xfc, 0x3a, 0x6f, 0x3a, 0x43, 0x60, 0xb7, 0xf1,
		0xc2, 0x24, 0x1a, 0xfd, 0x1b, 0xdc, 0xeb, 0x1c, 0x52, 0x7d, 0x16, 0xb2, 0x5e, 0xb2, 0x89, 0xc6,
		0x7f, 0x81, 0xe1, 0x7d, 0x0c, 0xf6, 0x40, 0x20, 0xd9, 0x45, 0x53, 0x7c, 0x91, 0x7b, 0x20, 0x80,
		0xc2, 0xd3, 0xa8, 0xbf, 0x80, 0x89, 0x66, 0xfa, 0x4d, 0x3e, 0x8d, 0xfa, 0xea, 0x17, 0x3c, 0x9a,
		0x64, 0xcd, 0x8f, 0xa6, 0xf8, 0x2d, 0x3e, 0x9a, 0xc4, 0x1e, 0x37, 0xa3, 0xbf, 0x22, 0x88, 0xe6,
		0xf8, 0x6d, 0xde, 0x8c, 0xbe, 0x82, 0xa0, 0xba, 0x0d, 0xe2, 0x60, 0x35, 0x10, 0xcd, 0xf7, 0x3b,
		0x8c, 0x6f, 0x6a, 0xa0, 0x18, 0xa8, 0x3e, 0x07, 0xc7, 0x86, 0x57, 0x02, 0xd1, 0xac, 0x5f, 0xba,
		0xdb, 0xb7, 0x77, 0x0b, 0x16, 0x02, 0xd5, 0x1d, 0x3f, 0xa5, 0x04, 0xab, 0x80, 0x68, 0xda, 0x57,
		0xee, 0x86, 0x17, 0xee, 0x60, 0x11, 0x50, 0xad, 0x01, 0xf8, 0x09, 0x38, 0x9a, 0xeb, 0x55, 0xc6,
		0x15, 0x00, 0xe1, 0xa9, 0xc1, 0xf2, 0x6f, 0x34, 0xfe, 0xcb, 0x7c, 0x6a, 0x30, 0x04, 0x9e, 0x1a,
		0x3c, 0xf5, 0x46, 0xa3, 0x5f, 0xe3, 0x53, 0x83, 0x43, 0x70, 0x64, 0x07, 0xb2, 0x5b, 0x34, 0xc3,
		0x57, 0x78, 0x64, 0x07, 0x50, 0xd5, 0x2d, 0x98, 0x1a, 0x48, 0x88, 0xd1, 0x54, 0x5f, 0x65, 0x54,
		0x42, 0x7f, 0x3e, 0x0c, 0x26, 0x2f, 0x96, 0x0c, 0xa3, 0xd9, 0xfe, 0xa0, 0x2f, 0x79, 0xb1, 0x5c,
		0x58, 0xbd, 0x0c, 0x19, 0xa3, 0xa7, 0xeb, 0x78, 0xf2, 0x88, 0xf7, 0xfe, 0x96, 0xb0, 0xf8, 0xef,
		0x1f, 0x30, 0xef, 0x70, 0x40, 0x75, 0x11, 0x52, 0xa8, 0xdb, 0x42, 0xed, 0x28, 0xe4, 0x7f, 0x7c,
		0xc0, 0x17, 0x4c, 0x6c, 0x5d, 0x7d, 0x16, 0x80, 0x1e, 0x8d, 0x90, 0xcb, 0xc3, 0x08, 0xec, 0x7f,
		0x7e, 0xc0, 0x3e, 0xde, 0xf1, 0x21, 0x3e, 0x01, 0xfd, 0x14, 0xe8, 0xde, 0x04, 0xef, 0x86, 0x09,
		0xc8, 0x88, 0x5c, 0x82, 0xf1, 0x6b, 0x8e, 0x69, 0xb8, 0x4a, 0x27, 0x0a, 0xfd, 0x5f, 0x0c, 0xcd,
		0xed, 0xb1, 0xc3, 0xba, 0xa6, 0x8d, 0x5c, 0xa5, 0xe3, 0x44, 0x61, 0xff, 0x9b, 0x61, 0x3d, 0x00,
		0x06, 0xab, 0x8a, 0xe3, 0x8e, 0xd2, 0xef, 0xff, 0xe1, 0x60, 0x0e, 0xc0, 0x8d, 0xc6, 0xbf, 0xaf,
		0xa3, 0x83, 0x28, 0xec, 0x7b, 0xbc, 0xd1, 0xcc, 0xbe, 0xfa, 0x29, 0xc8, 0xe2, 0x9f, 0xf4, 0x8b,
		0xbc, 0x08, 0xf0, 0xff, 0x32, 0xb0, 0x8f, 0xc0, 0x6f, 0x76, 0xdc, 0xb6, 0xab, 0x45, 0x3b, 0xfb,
		0xff, 0xd8, 0x48, 0x73, 0xfb, 0x6a, 0x0d, 0x72, 0x8e, 0xdb, 0x6e, 0xf7, 0x58, 0x7d, 0x1a, 0x01,
		0xff, 0xe1, 0x07, 0xde, 0x91, 0x85, 0x87, 0xc1, 0xa3, 0x7d, 0xf3, 0xba, 0x6b, 0x99, 0xe4, 0xc2,
		0x23, 0x8a, 0xe1, 0x2e, 0x63, 0x08, 0x40, 0xaa, 0xcb, 0x90, 0xc7, 0x7d, 0xb1, 0x91, 0x85, 0xc8,
		0xed, 0x54, 0x04, 0xc5, 0xff, 0x33, 0x07, 0x84, 0x40, 0x4b, 0x57, 0x87, 0x9f, 0x06, 0xc3, 0xaa,
		0xb9, 0x6a, 0xd2, 0x73, 0xe0, 0x17, 0x1f, 0xed, 0x68, 0xee, 0x7e, 0xaf, 0x55, 0x51, 0xcd, 0xee,
		0xbc, 0x6a, 0x3a, 0x5d, 0xd3, 0x99, 0x0f, 0x9f, 0xdf, 0x92, 0x5f, 0xf0, 0xcd, 0x14, 0x9c, 0x26,
		0xdf, 0xfb, 0x9e, 0x9d, 0x57, 0xcd, 0x6e, 0xcb, 0x74, 0xe6, 0xbd, 0xd5, 0x7d, 0xde, 0x34, 0x18,
		0xb7, 0x78, 0x9c, 0x9a, 0x54, 0xa8, 0x49, 0xc5, 0x33, 0x99, 0x1d, 0x7a, 0x26, 0x5c, 0x3e, 0x01,
		0xa9, 0x66, 0xaf, 0xd5, 0x3a, 0x10, 0x05, 0x48, 0x38, 0xbd, 0x16, 0xfb, 0x42, 0x0c, 0xff, 0x2c,
		0xbf, 0x97, 0x80, 0x5c, 0x53, 0xe9, 0x5a, 0x3a, 0x6a, 0x18, 0xa8, 0xb1, 0x27, 0x16, 0x21, 0x4d,
		0xfa, 0xfb, 0x0c, 0x31, 0x8a, 0x5d, 0x1d, 0x93, 0xd8, 0xb3, 0xa7, 0x59, 0x20, 0xa7, 0xe6, 0x71,
		0x4f, 0xb3, 0xe0, 0x69, 0xce, 0xd2, 0x43, 0x73, 0x4f, 0x73, 0xd6, 0xd3, 0x9c, 0x23, 0x47, 0xe7,
		0x09, 0x4f, 0x73, 0xce, 0xd3, 0x2c, 0x92, 0xab, 0xa1, 0x09, 0x4f, 0xb3, 0xe8, 0x69, 0xce, 0x93,
		0xcb, 0xa0, 0xa4, 0xa7, 0x39, 0xef, 0x69, 0x2e, 0x90, 0x3b, 0xa0, 0x29, 0x4f, 0x73, 0xc1, 0xd3,
		0x5c, 0x24, 0xf7, 0x3e, 0xa2, 0xa7, 0xb9, 0xe8, 0x69, 0x2e, 0x91, 0x0f, 0xc1, 0xc6, 0x3d, 0xcd,
		0x25, 0x71, 0x16, 0xc6, 0x69, 0xcf, 0x9e, 0x26, 0x1f, 0x0a, 0x4c, 0x5e, 0x1d, 0x93, 0xb8, 0xc0,
		0xd7, 0x3d, 0x43, 0x3e, 0xf6, 0x4a, 0xfb, 0xba, 0x67, 0x7c, 0xdd, 0x02, 0xf9, 0xe7, 0x14, 0xc1,
		0xd7, 0x2d, 0xf8, 0xba, 0xb3, 0xc5, 0x09, 0x1c, 0x69, 0xbe, 0xee, 0xac, 0xaf, 0x3b, 0x57, 0x2c,
		0x60, 0xff, 0xfb, 0xba, 0x73, 0xbe, 0x6e, 0x91, 0x7c, 0x00, 0x91, 0xf7, 0x75, 0x8b, 0x22, 0x9e,
		0x24, 0xbd, 0x96, 0xcc, 0x72, 0x06, 0xf9, 0xa8, 0x2c, 0xb7, 0x50, 0xaa, 0x1c, 0x11, 0x01, 0x15,
		0x32, 0xd0, 0x57, 0xc7, 0x24, 0x70, 0x7a, 0x2d, 0xb6, 0xcc, 0x2f, 0xe5, 0x81, 0x9c, 0x6e, 0xc9,
		0x04, 0xb3, 0x74, 0xf5, 0xcd, 0x3b, 0xa5, 0xb1, 0xef, 0xdd, 0x29, 0x8d, 0xfd, 0xeb, 0x9d, 0xd2,
		0xd8, 0x5b, 0x77, 0x4a, 0xb1, 0xf7, 0xee, 0x94, 0x62, 0xef, 0xdf, 0x29, 0xc5, 0x6e, 0x1f, 0x96,
		0x62, 0x6f, 0x1c, 0x96, 0x62, 0x5f, 0x3f, 0x2c, 0xc5, 0xbe, 0x7d, 0x58, 0x8a, 0xbd, 0x79, 0x58,
		0x8a, 0x7d, 0xef, 0xb0, 0x34, 0xf6, 0xd6, 0x61, 0x29, 0xf6, 0x83, 0xc3, 0xd2, 0xd8, 0x7b, 0x87,
		0xa5, 0xd8, 0xfb, 0x87, 0xa5, 0xb1, 0xdb, 0x6f, 0x97, 0xc6, 0xde, 0x78, 0xbb, 0x14, 0x6b, 0xa5,
		0xe9, 0xe7, 0xe1, 0x3f, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x8a, 0xff, 0x45, 0xc7, 0x83, 0x36, 0x00,
		0x00,
	}
	r := bytes.NewReader(gzipped)
	gzipr, err := compress_gzip.NewReader(r)
	if err != nil {
		panic(err)
	}
	ungzipped, err := io_ioutil.ReadAll(gzipr)
	if err != nil {
		panic(err)
	}
	if err := github_com_cosmos_gogoproto_proto.Unmarshal(ungzipped, d); err != nil {
		panic(err)
	}
	return d
}
func (this *Subby) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Subby)
	if !ok {
		that2, ok := that.(Subby)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Subby")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Subby but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Subby but is not nil && this == nil")
	}
	if this.Sub != that1.Sub {
		return fmt.Errorf("Sub this(%v) Not Equal that(%v)", this.Sub, that1.Sub)
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *Subby) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Subby)
	if !ok {
		that2, ok := that.(Subby)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Sub != that1.Sub {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *SampleOneOf) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf)
	if !ok {
		that2, ok := that.(SampleOneOf)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf but is not nil && this == nil")
	}
	if that1.TestOneof == nil {
		if this.TestOneof != nil {
			return fmt.Errorf("this.TestOneof != nil && that1.TestOneof == nil")
		}
	} else if this.TestOneof == nil {
		return fmt.Errorf("this.TestOneof == nil && that1.TestOneof != nil")
	} else if err := this.TestOneof.VerboseEqual(that1.TestOneof); err != nil {
		return err
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return fmt.Errorf("XXX_unrecognized this(%v) Not Equal that(%v)", this.XXX_unrecognized, that1.XXX_unrecognized)
	}
	return nil
}
func (this *SampleOneOf_Field1) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field1)
	if !ok {
		that2, ok := that.(SampleOneOf_Field1)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field1")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field1 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field1 but is not nil && this == nil")
	}
	if this.Field1 != that1.Field1 {
		return fmt.Errorf("Field1 this(%v) Not Equal that(%v)", this.Field1, that1.Field1)
	}
	return nil
}
func (this *SampleOneOf_Field2) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field2)
	if !ok {
		that2, ok := that.(SampleOneOf_Field2)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field2")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field2 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field2 but is not nil && this == nil")
	}
	if this.Field2 != that1.Field2 {
		return fmt.Errorf("Field2 this(%v) Not Equal that(%v)", this.Field2, that1.Field2)
	}
	return nil
}
func (this *SampleOneOf_Field3) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field3)
	if !ok {
		that2, ok := that.(SampleOneOf_Field3)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field3")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field3 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field3 but is not nil && this == nil")
	}
	if this.Field3 != that1.Field3 {
		return fmt.Errorf("Field3 this(%v) Not Equal that(%v)", this.Field3, that1.Field3)
	}
	return nil
}
func (this *SampleOneOf_Field4) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field4)
	if !ok {
		that2, ok := that.(SampleOneOf_Field4)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field4")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field4 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field4 but is not nil && this == nil")
	}
	if this.Field4 != that1.Field4 {
		return fmt.Errorf("Field4 this(%v) Not Equal that(%v)", this.Field4, that1.Field4)
	}
	return nil
}
func (this *SampleOneOf_Field5) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field5)
	if !ok {
		that2, ok := that.(SampleOneOf_Field5)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field5")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field5 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field5 but is not nil && this == nil")
	}
	if this.Field5 != that1.Field5 {
		return fmt.Errorf("Field5 this(%v) Not Equal that(%v)", this.Field5, that1.Field5)
	}
	return nil
}
func (this *SampleOneOf_Field6) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field6)
	if !ok {
		that2, ok := that.(SampleOneOf_Field6)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field6")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field6 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field6 but is not nil && this == nil")
	}
	if this.Field6 != that1.Field6 {
		return fmt.Errorf("Field6 this(%v) Not Equal that(%v)", this.Field6, that1.Field6)
	}
	return nil
}
func (this *SampleOneOf_Field7) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field7)
	if !ok {
		that2, ok := that.(SampleOneOf_Field7)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field7")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field7 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field7 but is not nil && this == nil")
	}
	if this.Field7 != that1.Field7 {
		return fmt.Errorf("Field7 this(%v) Not Equal that(%v)", this.Field7, that1.Field7)
	}
	return nil
}
func (this *SampleOneOf_Field8) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field8)
	if !ok {
		that2, ok := that.(SampleOneOf_Field8)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field8")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field8 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field8 but is not nil && this == nil")
	}
	if this.Field8 != that1.Field8 {
		return fmt.Errorf("Field8 this(%v) Not Equal that(%v)", this.Field8, that1.Field8)
	}
	return nil
}
func (this *SampleOneOf_Field9) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field9)
	if !ok {
		that2, ok := that.(SampleOneOf_Field9)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field9")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field9 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field9 but is not nil && this == nil")
	}
	if this.Field9 != that1.Field9 {
		return fmt.Errorf("Field9 this(%v) Not Equal that(%v)", this.Field9, that1.Field9)
	}
	return nil
}
func (this *SampleOneOf_Field10) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field10)
	if !ok {
		that2, ok := that.(SampleOneOf_Field10)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field10")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field10 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field10 but is not nil && this == nil")
	}
	if this.Field10 != that1.Field10 {
		return fmt.Errorf("Field10 this(%v) Not Equal that(%v)", this.Field10, that1.Field10)
	}
	return nil
}
func (this *SampleOneOf_Field11) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field11)
	if !ok {
		that2, ok := that.(SampleOneOf_Field11)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field11")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field11 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field11 but is not nil && this == nil")
	}
	if this.Field11 != that1.Field11 {
		return fmt.Errorf("Field11 this(%v) Not Equal that(%v)", this.Field11, that1.Field11)
	}
	return nil
}
func (this *SampleOneOf_Field12) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field12)
	if !ok {
		that2, ok := that.(SampleOneOf_Field12)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field12")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field12 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field12 but is not nil && this == nil")
	}
	if this.Field12 != that1.Field12 {
		return fmt.Errorf("Field12 this(%v) Not Equal that(%v)", this.Field12, that1.Field12)
	}
	return nil
}
func (this *SampleOneOf_Field13) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field13)
	if !ok {
		that2, ok := that.(SampleOneOf_Field13)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field13")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field13 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field13 but is not nil && this == nil")
	}
	if this.Field13 != that1.Field13 {
		return fmt.Errorf("Field13 this(%v) Not Equal that(%v)", this.Field13, that1.Field13)
	}
	return nil
}
func (this *SampleOneOf_Field14) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field14)
	if !ok {
		that2, ok := that.(SampleOneOf_Field14)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field14")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field14 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field14 but is not nil && this == nil")
	}
	if this.Field14 != that1.Field14 {
		return fmt.Errorf("Field14 this(%v) Not Equal that(%v)", this.Field14, that1.Field14)
	}
	return nil
}
func (this *SampleOneOf_Field15) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field15)
	if !ok {
		that2, ok := that.(SampleOneOf_Field15)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field15")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field15 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field15 but is not nil && this == nil")
	}
	if !bytes.Equal(this.Field15, that1.Field15) {
		return fmt.Errorf("Field15 this(%v) Not Equal that(%v)", this.Field15, that1.Field15)
	}
	return nil
}
func (this *SampleOneOf_SubMessage) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_SubMessage)
	if !ok {
		that2, ok := that.(SampleOneOf_SubMessage)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_SubMessage")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_SubMessage but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_SubMessage but is not nil && this == nil")
	}
	if !this.SubMessage.Equal(that1.SubMessage) {
		return fmt.Errorf("SubMessage this(%v) Not Equal that(%v)", this.SubMessage, that1.SubMessage)
	}
	return nil
}
func (this *SampleOneOf) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf)
	if !ok {
		that2, ok := that.(SampleOneOf)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.TestOneof == nil {
		if this.TestOneof != nil {
			return false
		}
	} else if this.TestOneof == nil {
		return false
	} else if !this.TestOneof.Equal(that1.TestOneof) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *SampleOneOf_Field1) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field1)
	if !ok {
		that2, ok := that.(SampleOneOf_Field1)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field1 != that1.Field1 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field2) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field2)
	if !ok {
		that2, ok := that.(SampleOneOf_Field2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field2 != that1.Field2 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field3) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field3)
	if !ok {
		that2, ok := that.(SampleOneOf_Field3)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field3 != that1.Field3 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field4) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field4)
	if !ok {
		that2, ok := that.(SampleOneOf_Field4)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field4 != that1.Field4 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field5) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field5)
	if !ok {
		that2, ok := that.(SampleOneOf_Field5)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field5 != that1.Field5 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field6) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field6)
	if !ok {
		that2, ok := that.(SampleOneOf_Field6)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field6 != that1.Field6 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field7) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field7)
	if !ok {
		that2, ok := that.(SampleOneOf_Field7)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field7 != that1.Field7 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field8) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field8)
	if !ok {
		that2, ok := that.(SampleOneOf_Field8)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field8 != that1.Field8 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field9) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field9)
	if !ok {
		that2, ok := that.(SampleOneOf_Field9)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field9 != that1.Field9 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field10) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field10)
	if !ok {
		that2, ok := that.(SampleOneOf_Field10)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field10 != that1.Field10 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field11) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field11)
	if !ok {
		that2, ok := that.(SampleOneOf_Field11)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field11 != that1.Field11 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field12) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field12)
	if !ok {
		that2, ok := that.(SampleOneOf_Field12)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field12 != that1.Field12 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field13) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field13)
	if !ok {
		that2, ok := that.(SampleOneOf_Field13)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field13 != that1.Field13 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field14) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field14)
	if !ok {
		that2, ok := that.(SampleOneOf_Field14)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Field14 != that1.Field14 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field15) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_Field15)
	if !ok {
		that2, ok := that.(SampleOneOf_Field15)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Field15, that1.Field15) {
		return false
	}
	return true
}
func (this *SampleOneOf_SubMessage) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SampleOneOf_SubMessage)
	if !ok {
		that2, ok := that.(SampleOneOf_SubMessage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.SubMessage.Equal(that1.SubMessage) {
		return false
	}
	return true
}
func (this *Subby) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&oneof3_combos_marshaler.Subby{")
	s = append(s, "Sub: "+fmt.Sprintf("%#v", this.Sub)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SampleOneOf) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 20)
	s = append(s, "&oneof3_combos_marshaler.SampleOneOf{")
	if this.TestOneof != nil {
		s = append(s, "TestOneof: "+fmt.Sprintf("%#v", this.TestOneof)+",\n")
	}
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SampleOneOf_Field1) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field1{` +
		`Field1:` + fmt.Sprintf("%#v", this.Field1) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field2) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field2{` +
		`Field2:` + fmt.Sprintf("%#v", this.Field2) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field3) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field3{` +
		`Field3:` + fmt.Sprintf("%#v", this.Field3) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field4) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field4{` +
		`Field4:` + fmt.Sprintf("%#v", this.Field4) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field5) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field5{` +
		`Field5:` + fmt.Sprintf("%#v", this.Field5) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field6) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field6{` +
		`Field6:` + fmt.Sprintf("%#v", this.Field6) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field7) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field7{` +
		`Field7:` + fmt.Sprintf("%#v", this.Field7) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field8) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field8{` +
		`Field8:` + fmt.Sprintf("%#v", this.Field8) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field9) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field9{` +
		`Field9:` + fmt.Sprintf("%#v", this.Field9) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field10) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field10{` +
		`Field10:` + fmt.Sprintf("%#v", this.Field10) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field11) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field11{` +
		`Field11:` + fmt.Sprintf("%#v", this.Field11) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field12) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field12{` +
		`Field12:` + fmt.Sprintf("%#v", this.Field12) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field13) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field13{` +
		`Field13:` + fmt.Sprintf("%#v", this.Field13) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field14) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field14{` +
		`Field14:` + fmt.Sprintf("%#v", this.Field14) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field15) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_Field15{` +
		`Field15:` + fmt.Sprintf("%#v", this.Field15) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_SubMessage) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&oneof3_combos_marshaler.SampleOneOf_SubMessage{` +
		`SubMessage:` + fmt.Sprintf("%#v", this.SubMessage) + `}`}, ", ")
	return s
}
func valueToGoStringOne(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Subby) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Subby) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Subby) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Sub) > 0 {
		i -= len(m.Sub)
		copy(dAtA[i:], m.Sub)
		i = encodeVarintOne(dAtA, i, uint64(len(m.Sub)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SampleOneOf) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SampleOneOf) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.TestOneof != nil {
		{
			size := m.TestOneof.Size()
			i -= size
			if _, err := m.TestOneof.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *SampleOneOf_Field1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 8
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Field1))))
	i--
	dAtA[i] = 0x9
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 4
	encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Field2))))
	i--
	dAtA[i] = 0x15
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field3) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field3) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintOne(dAtA, i, uint64(m.Field3))
	i--
	dAtA[i] = 0x18
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field4) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field4) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintOne(dAtA, i, uint64(m.Field4))
	i--
	dAtA[i] = 0x20
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field5) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field5) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintOne(dAtA, i, uint64(m.Field5))
	i--
	dAtA[i] = 0x28
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field6) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field6) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintOne(dAtA, i, uint64(m.Field6))
	i--
	dAtA[i] = 0x30
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field7) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field7) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintOne(dAtA, i, uint64((uint32(m.Field7)<<1)^uint32((m.Field7>>31))))
	i--
	dAtA[i] = 0x38
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field8) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field8) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintOne(dAtA, i, uint64((uint64(m.Field8)<<1)^uint64((m.Field8>>63))))
	i--
	dAtA[i] = 0x40
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field9) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field9) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 4
	encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(m.Field9))
	i--
	dAtA[i] = 0x4d
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field10) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field10) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 4
	encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(m.Field10))
	i--
	dAtA[i] = 0x55
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field11) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field11) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 8
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(m.Field11))
	i--
	dAtA[i] = 0x59
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field12) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field12) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= 8
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(m.Field12))
	i--
	dAtA[i] = 0x61
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field13) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field13) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i--
	if m.Field13 {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x68
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field14) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field14) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.Field14)
	copy(dAtA[i:], m.Field14)
	i = encodeVarintOne(dAtA, i, uint64(len(m.Field14)))
	i--
	dAtA[i] = 0x72
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_Field15) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_Field15) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Field15 != nil {
		i -= len(m.Field15)
		copy(dAtA[i:], m.Field15)
		i = encodeVarintOne(dAtA, i, uint64(len(m.Field15)))
		i--
		dAtA[i] = 0x7a
	}
	return len(dAtA) - i, nil
}
func (m *SampleOneOf_SubMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SampleOneOf_SubMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.SubMessage != nil {
		{
			size, err := m.SubMessage.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOne(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	return len(dAtA) - i, nil
}
func encodeVarintOne(dAtA []byte, offset int, v uint64) int {
	offset -= sovOne(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func NewPopulatedSubby(r randyOne, easy bool) *Subby {
	this := &Subby{}
	this.Sub = string(randStringOne(r))
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedOne(r, 2)
	}
	return this
}

func NewPopulatedSampleOneOf(r randyOne, easy bool) *SampleOneOf {
	this := &SampleOneOf{}
	oneofNumber_TestOneof := []int32{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}[r.Intn(16)]
	switch oneofNumber_TestOneof {
	case 1:
		this.TestOneof = NewPopulatedSampleOneOf_Field1(r, easy)
	case 2:
		this.TestOneof = NewPopulatedSampleOneOf_Field2(r, easy)
	case 3:
		this.TestOneof = NewPopulatedSampleOneOf_Field3(r, easy)
	case 4:
		this.TestOneof = NewPopulatedSampleOneOf_Field4(r, easy)
	case 5:
		this.TestOneof = NewPopulatedSampleOneOf_Field5(r, easy)
	case 6:
		this.TestOneof = NewPopulatedSampleOneOf_Field6(r, easy)
	case 7:
		this.TestOneof = NewPopulatedSampleOneOf_Field7(r, easy)
	case 8:
		this.TestOneof = NewPopulatedSampleOneOf_Field8(r, easy)
	case 9:
		this.TestOneof = NewPopulatedSampleOneOf_Field9(r, easy)
	case 10:
		this.TestOneof = NewPopulatedSampleOneOf_Field10(r, easy)
	case 11:
		this.TestOneof = NewPopulatedSampleOneOf_Field11(r, easy)
	case 12:
		this.TestOneof = NewPopulatedSampleOneOf_Field12(r, easy)
	case 13:
		this.TestOneof = NewPopulatedSampleOneOf_Field13(r, easy)
	case 14:
		this.TestOneof = NewPopulatedSampleOneOf_Field14(r, easy)
	case 15:
		this.TestOneof = NewPopulatedSampleOneOf_Field15(r, easy)
	case 16:
		this.TestOneof = NewPopulatedSampleOneOf_SubMessage(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
		this.XXX_unrecognized = randUnrecognizedOne(r, 17)
	}
	return this
}

func NewPopulatedSampleOneOf_Field1(r randyOne, easy bool) *SampleOneOf_Field1 {
	this := &SampleOneOf_Field1{}
	this.Field1 = float64(r.Float64())
	if r.Intn(2) == 0 {
		this.Field1 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field2(r randyOne, easy bool) *SampleOneOf_Field2 {
	this := &SampleOneOf_Field2{}
	this.Field2 = float32(r.Float32())
	if r.Intn(2) == 0 {
		this.Field2 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field3(r randyOne, easy bool) *SampleOneOf_Field3 {
	this := &SampleOneOf_Field3{}
	this.Field3 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field3 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field4(r randyOne, easy bool) *SampleOneOf_Field4 {
	this := &SampleOneOf_Field4{}
	this.Field4 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Field4 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field5(r randyOne, easy bool) *SampleOneOf_Field5 {
	this := &SampleOneOf_Field5{}
	this.Field5 = uint32(r.Uint32())
	return this
}
func NewPopulatedSampleOneOf_Field6(r randyOne, easy bool) *SampleOneOf_Field6 {
	this := &SampleOneOf_Field6{}
	this.Field6 = uint64(uint64(r.Uint32()))
	return this
}
func NewPopulatedSampleOneOf_Field7(r randyOne, easy bool) *SampleOneOf_Field7 {
	this := &SampleOneOf_Field7{}
	this.Field7 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field7 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field8(r randyOne, easy bool) *SampleOneOf_Field8 {
	this := &SampleOneOf_Field8{}
	this.Field8 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Field8 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field9(r randyOne, easy bool) *SampleOneOf_Field9 {
	this := &SampleOneOf_Field9{}
	this.Field9 = uint32(r.Uint32())
	return this
}
func NewPopulatedSampleOneOf_Field10(r randyOne, easy bool) *SampleOneOf_Field10 {
	this := &SampleOneOf_Field10{}
	this.Field10 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field10 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field11(r randyOne, easy bool) *SampleOneOf_Field11 {
	this := &SampleOneOf_Field11{}
	this.Field11 = uint64(uint64(r.Uint32()))
	return this
}
func NewPopulatedSampleOneOf_Field12(r randyOne, easy bool) *SampleOneOf_Field12 {
	this := &SampleOneOf_Field12{}
	this.Field12 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Field12 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field13(r randyOne, easy bool) *SampleOneOf_Field13 {
	this := &SampleOneOf_Field13{}
	this.Field13 = bool(bool(r.Intn(2) == 0))
	return this
}
func NewPopulatedSampleOneOf_Field14(r randyOne, easy bool) *SampleOneOf_Field14 {
	this := &SampleOneOf_Field14{}
	this.Field14 = string(randStringOne(r))
	return this
}
func NewPopulatedSampleOneOf_Field15(r randyOne, easy bool) *SampleOneOf_Field15 {
	this := &SampleOneOf_Field15{}
	v1 := r.Intn(100)
	this.Field15 = make([]byte, v1)
	for i := 0; i < v1; i++ {
		this.Field15[i] = byte(r.Intn(256))
	}
	return this
}
func NewPopulatedSampleOneOf_SubMessage(r randyOne, easy bool) *SampleOneOf_SubMessage {
	this := &SampleOneOf_SubMessage{}
	this.SubMessage = NewPopulatedSubby(r, easy)
	return this
}

type randyOne interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneOne(r randyOne) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringOne(r randyOne) string {
	v2 := r.Intn(100)
	tmps := make([]rune, v2)
	for i := 0; i < v2; i++ {
		tmps[i] = randUTF8RuneOne(r)
	}
	return string(tmps)
}
func randUnrecognizedOne(r randyOne, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldOne(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldOne(dAtA []byte, r randyOne, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateOne(dAtA, uint64(key))
		v3 := r.Int63()
		if r.Intn(2) == 0 {
			v3 *= -1
		}
		dAtA = encodeVarintPopulateOne(dAtA, uint64(v3))
	case 1:
		dAtA = encodeVarintPopulateOne(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateOne(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateOne(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateOne(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateOne(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Subby) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sub)
	if l > 0 {
		n += 1 + l + sovOne(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SampleOneOf) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TestOneof != nil {
		n += m.TestOneof.Size()
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SampleOneOf_Field1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 9
	return n
}
func (m *SampleOneOf_Field2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 5
	return n
}
func (m *SampleOneOf_Field3) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field3))
	return n
}
func (m *SampleOneOf_Field4) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field4))
	return n
}
func (m *SampleOneOf_Field5) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field5))
	return n
}
func (m *SampleOneOf_Field6) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field6))
	return n
}
func (m *SampleOneOf_Field7) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sozOne(uint64(m.Field7))
	return n
}
func (m *SampleOneOf_Field8) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sozOne(uint64(m.Field8))
	return n
}
func (m *SampleOneOf_Field9) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 5
	return n
}
func (m *SampleOneOf_Field10) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 5
	return n
}
func (m *SampleOneOf_Field11) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 9
	return n
}
func (m *SampleOneOf_Field12) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 9
	return n
}
func (m *SampleOneOf_Field13) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 2
	return n
}
func (m *SampleOneOf_Field14) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Field14)
	n += 1 + l + sovOne(uint64(l))
	return n
}
func (m *SampleOneOf_Field15) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Field15 != nil {
		l = len(m.Field15)
		n += 1 + l + sovOne(uint64(l))
	}
	return n
}
func (m *SampleOneOf_SubMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubMessage != nil {
		l = m.SubMessage.Size()
		n += 2 + l + sovOne(uint64(l))
	}
	return n
}

func sovOne(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOne(x uint64) (n int) {
	return sovOne(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Subby) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Subby{`,
		`Sub:` + fmt.Sprintf("%v", this.Sub) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf{`,
		`TestOneof:` + fmt.Sprintf("%v", this.TestOneof) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field1) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field1{`,
		`Field1:` + fmt.Sprintf("%v", this.Field1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field2) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field2{`,
		`Field2:` + fmt.Sprintf("%v", this.Field2) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field3) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field3{`,
		`Field3:` + fmt.Sprintf("%v", this.Field3) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field4) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field4{`,
		`Field4:` + fmt.Sprintf("%v", this.Field4) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field5) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field5{`,
		`Field5:` + fmt.Sprintf("%v", this.Field5) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field6) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field6{`,
		`Field6:` + fmt.Sprintf("%v", this.Field6) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field7) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field7{`,
		`Field7:` + fmt.Sprintf("%v", this.Field7) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field8) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field8{`,
		`Field8:` + fmt.Sprintf("%v", this.Field8) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field9) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field9{`,
		`Field9:` + fmt.Sprintf("%v", this.Field9) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field10) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field10{`,
		`Field10:` + fmt.Sprintf("%v", this.Field10) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field11) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field11{`,
		`Field11:` + fmt.Sprintf("%v", this.Field11) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field12) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field12{`,
		`Field12:` + fmt.Sprintf("%v", this.Field12) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field13) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field13{`,
		`Field13:` + fmt.Sprintf("%v", this.Field13) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field14) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field14{`,
		`Field14:` + fmt.Sprintf("%v", this.Field14) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field15) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field15{`,
		`Field15:` + fmt.Sprintf("%v", this.Field15) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_SubMessage) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_SubMessage{`,
		`SubMessage:` + strings.Replace(fmt.Sprintf("%v", this.SubMessage), "Subby", "Subby", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringOne(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
