// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: google/protobuf/struct.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// `NullValue` is a singleton enumeration to represent the null value for the
// `Value` type union.
//
//	The JSON representation for `NullValue` is JSON `null`.
type NullValue int32

const (
	// Null value.
	NullValue_NULL_VALUE NullValue = 0
)

var NullValue_name = map[int32]string{
	0: "NULL_VALUE",
}

var NullValue_value = map[string]int32{
	"NULL_VALUE": 0,
}

func (x NullValue) String() string {
	return proto.EnumName(NullValue_name, int32(x))
}

func (NullValue) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_df322afd6c9fb402, []int{0}
}

func (NullValue) XXX_WellKnownType() string { return "NullValue" }

// `Struct` represents a structured data value, consisting of fields
// which map to dynamically typed values. In some languages, `Struct`
// might be supported by a native representation. For example, in
// scripting languages like JS a struct is represented as an
// object. The details of that representation are described together
// with the proto support for the language.
//
// The JSON representation for `Struct` is JSON object.
type Struct struct {
	// Unordered map of dynamically typed values.
	Fields               map[string]*Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Struct) Reset()         { *m = Struct{} }
func (m *Struct) String() string { return proto.CompactTextString(m) }
func (*Struct) ProtoMessage()    {}
func (*Struct) Descriptor() ([]byte, []int) {
	return fileDescriptor_df322afd6c9fb402, []int{0}
}
func (*Struct) XXX_WellKnownType() string { return "Struct" }
func (m *Struct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Struct.Unmarshal(m, b)
}
func (m *Struct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Struct.Marshal(b, m, deterministic)
}
func (m *Struct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Struct.Merge(m, src)
}
func (m *Struct) XXX_Size() int {
	return xxx_messageInfo_Struct.Size(m)
}
func (m *Struct) XXX_DiscardUnknown() {
	xxx_messageInfo_Struct.DiscardUnknown(m)
}

var xxx_messageInfo_Struct proto.InternalMessageInfo

func (m *Struct) GetFields() map[string]*Value {
	if m != nil {
		return m.Fields
	}
	return nil
}

// `Value` represents a dynamically typed value which can be either
// null, a number, a string, a boolean, a recursive struct value, or a
// list of values. A producer of value is expected to set one of that
// variants, absence of any variant indicates an error.
//
// The JSON representation for `Value` is JSON value.
type Value struct {
	// The kind of value.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_NullValue
	//	*Value_NumberValue
	//	*Value_StringValue
	//	*Value_BoolValue
	//	*Value_StructValue
	//	*Value_ListValue
	Kind                 isValue_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_df322afd6c9fb402, []int{1}
}
func (*Value) XXX_WellKnownType() string { return "Value" }
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Kind interface {
	isValue_Kind()
}

type Value_NullValue struct {
	NullValue NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof" json:"null_value,omitempty"`
}
type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,json=numberValue,proto3,oneof" json:"number_value,omitempty"`
}
type Value_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof" json:"string_value,omitempty"`
}
type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof" json:"bool_value,omitempty"`
}
type Value_StructValue struct {
	StructValue *Struct `protobuf:"bytes,5,opt,name=struct_value,json=structValue,proto3,oneof" json:"struct_value,omitempty"`
}
type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,6,opt,name=list_value,json=listValue,proto3,oneof" json:"list_value,omitempty"`
}

func (*Value_NullValue) isValue_Kind()   {}
func (*Value_NumberValue) isValue_Kind() {}
func (*Value_StringValue) isValue_Kind() {}
func (*Value_BoolValue) isValue_Kind()   {}
func (*Value_StructValue) isValue_Kind() {}
func (*Value_ListValue) isValue_Kind()   {}

func (m *Value) GetKind() isValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *Value) GetNullValue() NullValue {
	if x, ok := m.GetKind().(*Value_NullValue); ok {
		return x.NullValue
	}
	return NullValue_NULL_VALUE
}

func (m *Value) GetNumberValue() float64 {
	if x, ok := m.GetKind().(*Value_NumberValue); ok {
		return x.NumberValue
	}
	return 0
}

func (m *Value) GetStringValue() string {
	if x, ok := m.GetKind().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Value) GetBoolValue() bool {
	if x, ok := m.GetKind().(*Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *Value) GetStructValue() *Struct {
	if x, ok := m.GetKind().(*Value_StructValue); ok {
		return x.StructValue
	}
	return nil
}

func (m *Value) GetListValue() *ListValue {
	if x, ok := m.GetKind().(*Value_ListValue); ok {
		return x.ListValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_NullValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_StructValue)(nil),
		(*Value_ListValue)(nil),
	}
}

// `ListValue` is a wrapper around a repeated field of values.
//
// The JSON representation for `ListValue` is JSON array.
type ListValue struct {
	// Repeated field of dynamically typed values.
	Values               []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListValue) Reset()         { *m = ListValue{} }
func (m *ListValue) String() string { return proto.CompactTextString(m) }
func (*ListValue) ProtoMessage()    {}
func (*ListValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_df322afd6c9fb402, []int{2}
}
func (*ListValue) XXX_WellKnownType() string { return "ListValue" }
func (m *ListValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListValue.Unmarshal(m, b)
}
func (m *ListValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListValue.Marshal(b, m, deterministic)
}
func (m *ListValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListValue.Merge(m, src)
}
func (m *ListValue) XXX_Size() int {
	return xxx_messageInfo_ListValue.Size(m)
}
func (m *ListValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ListValue.DiscardUnknown(m)
}

var xxx_messageInfo_ListValue proto.InternalMessageInfo

func (m *ListValue) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("google.protobuf.NullValue", NullValue_name, NullValue_value)
	proto.RegisterType((*Struct)(nil), "google.protobuf.Struct")
	proto.RegisterMapType((map[string]*Value)(nil), "google.protobuf.Struct.FieldsEntry")
	proto.RegisterType((*Value)(nil), "google.protobuf.Value")
	proto.RegisterType((*ListValue)(nil), "google.protobuf.ListValue")
}

func init() { proto.RegisterFile("google/protobuf/struct.proto", fileDescriptor_df322afd6c9fb402) }

var fileDescriptor_df322afd6c9fb402 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x8b, 0xd3, 0x40,
	0x14, 0xc6, 0x3b, 0xc9, 0x36, 0x98, 0x17, 0x59, 0x97, 0x11, 0xb4, 0xac, 0xa2, 0xa1, 0x7b, 0x09,
	0x22, 0x09, 0xd4, 0x8b, 0x58, 0x2f, 0x06, 0xd6, 0x2d, 0x18, 0x4a, 0x8c, 0xb6, 0x82, 0x97, 0xd2,
	0xa4, 0x69, 0x08, 0x9d, 0xce, 0x94, 0x64, 0x46, 0xe9, 0xc9, 0x7f, 0xc3, 0xb3, 0x47, 0x8f, 0xfe,
	0x75, 0x1e, 0x65, 0x66, 0x92, 0x54, 0x5a, 0x7a, 0xcb, 0x7b, 0xef, 0xf7, 0x7d, 0x33, 0xdf, 0xcb,
	0xc0, 0xd3, 0x82, 0xb1, 0x82, 0xe4, 0xc1, 0xae, 0x62, 0x9c, 0xa5, 0x62, 0x1d, 0xd4, 0xbc, 0x12,
	0x19, 0xf7, 0x55, 0x8d, 0x1f, 0xe8, 0xa9, 0xdf, 0x4e, 0x87, 0x3f, 0x11, 0x58, 0x9f, 0x14, 0x81,
	0xc7, 0x60, 0xad, 0xcb, 0x9c, 0xac, 0xea, 0x01, 0x72, 0x4d, 0xcf, 0x19, 0xdd, 0xf8, 0x47, 0xb0,
	0xaf, 0x41, 0xff, 0xbd, 0xa2, 0x6e, 0x29, 0xaf, 0xf6, 0x49, 0x23, 0xb9, 0xfe, 0x08, 0xce, 0x7f,
	0x6d, 0x7c, 0x05, 0xe6, 0x26, 0xdf, 0x0f, 0x90, 0x8b, 0x3c, 0x3b, 0x91, 0x9f, 0xf8, 0x25, 0xf4,
	0xbf, 0x2d, 0x89, 0xc8, 0x07, 0x86, 0x8b, 0x3c, 0x67, 0xf4, 0xe8, 0xc4, 0x7c, 0x2e, 0xa7, 0x89,
	0x86, 0xde, 0x18, 0xaf, 0xd1, 0xf0, 0x8f, 0x01, 0x7d, 0xd5, 0xc4, 0x63, 0x00, 0x2a, 0x08, 0x59,
	0x68, 0x03, 0x69, 0x7a, 0x39, 0xba, 0x3e, 0x31, 0x98, 0x0a, 0x42, 0x14, 0x3f, 0xe9, 0x25, 0x36,
	0x6d, 0x0b, 0x7c, 0x03, 0xf7, 0xa9, 0xd8, 0xa6, 0x79, 0xb5, 0x38, 0x9c, 0x8f, 0x26, 0xbd, 0xc4,
	0xd1, 0xdd, 0x0e, 0xaa, 0x79, 0x55, 0xd2, 0xa2, 0x81, 0x4c, 0x79, 0x71, 0x09, 0xe9, 0xae, 0x86,
	0x9e, 0x03, 0xa4, 0x8c, 0xb5, 0xd7, 0xb8, 0x70, 0x91, 0x77, 0x4f, 0x1e, 0x25, 0x7b, 0x1a, 0x78,
	0xab, 0x5c, 0x44, 0xc6, 0x1b, 0xa4, 0xaf, 0xa2, 0x3e, 0x3e, 0xb3, 0xc7, 0xc6, 0x5e, 0x64, 0xbc,
	0x4b, 0x49, 0xca, 0xba, 0xd5, 0x5a, 0x4a, 0x7b, 0x9a, 0x32, 0x2a, 0x6b, 0xde, 0xa5, 0x24, 0x6d,
	0x11, 0x5a, 0x70, 0xb1, 0x29, 0xe9, 0x6a, 0x38, 0x06, 0xbb, 0x23, 0xb0, 0x0f, 0x96, 0x32, 0x6b,
	0xff, 0xe8, 0xb9, 0xa5, 0x37, 0xd4, 0x8b, 0x27, 0x60, 0x77, 0x4b, 0xc4, 0x97, 0x00, 0xd3, 0x59,
	0x14, 0x2d, 0xe6, 0xef, 0xa2, 0xd9, 0xed, 0x55, 0x2f, 0xfc, 0x01, 0x0f, 0x33, 0xb6, 0x3d, 0x76,
	0x08, 0x1d, 0x1d, 0x26, 0x96, 0x75, 0x8c, 0xbe, 0x06, 0xcd, 0xbc, 0x60, 0x64, 0x49, 0x0b, 0x9f,
	0x55, 0xc5, 0xe1, 0x25, 0xf2, 0xfd, 0x2e, 0xaf, 0x83, 0x0d, 0x65, 0xdf, 0x69, 0xf3, 0x2a, 0x77,
	0xe9, 0x5f, 0x84, 0x7e, 0x19, 0xe6, 0x5d, 0x1c, 0xfe, 0x36, 0x9e, 0xdd, 0x69, 0x69, 0xdc, 0x5e,
	0xee, 0x4b, 0x4e, 0xc8, 0x07, 0x49, 0x7f, 0x96, 0xc2, 0xd4, 0x52, 0x46, 0xaf, 0xfe, 0x05, 0x00,
	0x00, 0xff, 0xff, 0x6f, 0xd0, 0xfa, 0x67, 0xe2, 0x02, 0x00, 0x00,
}
